### ISSUE TITLE
cockpit_portal: Wrong response when "Execute blueprint" while there is no blueprints

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#100]
**Description**
The Repo actions return a confirmed messages while there is no blueprints to be executed.

**Sequence**
- Create a new Repo.
- From the repo drop down menu choose "Reload all services, Execute blueprint OR install"

**Actual Result**
![screenshot from 2016-07-17 15-21-27](https://cloud.githubusercontent.com/assets/17981089/16900873/9c26bece-4c3a-11e6-853f-776d7b3c77e1.png)

![screenshot from 2016-07-17 15-21-40](https://cloud.githubusercontent.com/assets/17981089/16900875/a155e028-4c3a-11e6-81e6-0ec5d8d15b75.png)

![screenshot from 2016-07-17 15-21-58](https://cloud.githubusercontent.com/assets/17981089/16900876/a5b71ace-4c3a-11e6-9a3e-ec64d81adbe2.png)

**Expected result**
There is no blueprints to be executed.

**Software**
0.9

**Comment by zaibon** [comment]
Message needs to be updated.

**Comment by abdulrahmantkhalifa** [comment]
fixed in https://github.com/Jumpscale/jumpscale_portal8/commit/c39f03234547690c774a9769762bce63d7773bf3

**Comment by abdulrahmantkhalifa** [comment]
can only reproduce on the blueprint execute, as the other methods are no longer exposed to the user ; 
fixed in https://github.com/Jumpscale/jumpscale_portal8/commit/76e3a9b0d32bb6582f7d5953c472d9b0a9493d8e
