### ISSUE TITLE
cockpit_portal: The cockpit is crashing when try to install the blueprint

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#103]
**Description**
I faced the following internal server error when I'm trying to install the blueprint
![screenshot from 2016-07-18 10-54-57](https://cloud.githubusercontent.com/assets/17981089/16909991/af23296e-4cde-11e6-85e2-f6a3e4cf28bd.png)
https://cockpit-demo-3.aydo2.com/cockpit/repo?repo=islamTest_8

Hint: It was working find yesterday and suddenly its crashed

![screenshot from 2016-07-18 13-32-41](https://cloud.githubusercontent.com/assets/17981089/16913642/92a02c90-4cf4-11e6-81d4-13a46d438124.png)
![screenshot from 2016-07-18 13-32-55](https://cloud.githubusercontent.com/assets/17981089/16913644/95ee6ed4-4cf4-11e6-94ed-4f92b32c4ea5.png)

**Comment by lzonneke** [comment]
@islamTaha12 please add the blueprint used in this ticket
