### ISSUE TITLE
There is no cockpit API

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#104]
**Description**
The cockpit API page hasn't any APIs to be tested even If when I load it.
https://cockpit-demo-3.aydo2.com/api/apidocs/index.html?raml=api.raml
![screenshot from 2016-07-18 11-18-56](https://cloud.githubusercontent.com/assets/17981089/16910529/d020a0da-4ce1-11e6-8460-b2e801bd9764.png)

**Comment by zaibon** [comment]
File is there : https://cockpit-demo-3.aydo2.com/api/apidocs/api.raml
But it seems it contains some error. Probably someone did some changes in the file that are non valid.

**Comment by zaibon** [comment]
https://github.com/Jumpscale/jscockpit/blob/master/jscockpit/ays_api/specifications/api.raml#L588
This line reference `AYSFile` wich is defined no where. this is what cause the error in the api-console
