### ISSUE TITLE
cockpit_portal: Add version on the portal

### ISSUE THREAD

**Issue by lzonneke** [Jumpscale/jscockpit#105]
## Goal

have version available on the cockpit so that testing an support can trace back issues and validation

**Comment by zaibon** [comment]
https://github.com/Jumpscale/jscockpit/pull/117/files

**Comment by zaibon** [comment]
Need to double check this page is still in the current version (0.9) of the portal

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/jumpscale_portal8/commit/ebb34be56ee4e3de40d318e8418d555c8c85eae9

**Comment by ramezsaeed** [comment]
verified on 8.1.0rc1
version button is not responding
http://85.255.197.84:2282/

**Comment by john-kheir** [comment]
Verified on 8.1.0 rc1
