### ISSUE TITLE
Cannot delete a service without specifying a role

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#106]
When trying to delete a service, by selecting "Delete service" from the Actions menu of a Repository page (first screenshot), you are required to specify a role (second screenshot), you are not allowed to delete all services by leaving the fields empty.

![screen shot 2016-07-19 at 10 35 13](https://cloud.githubusercontent.com/assets/13795109/16943557/905e69e4-4d9c-11e6-837c-f2833f85e5c4.png)

![screen shot 2016-07-19 at 10 36 22](https://cloud.githubusercontent.com/assets/13795109/16943573/aac42a08-4d9c-11e6-924c-5090bab141b3.png)

**Comment by xmonader** [comment]
role!instancename is the complete identifier so you don't delete service by its instancename.

**Comment by yveskerwyn** [comment]
OK, but still can't I delete all services in a repository just by leaving the Role and Instance name empty?

**Comment by xmonader** [comment]
Deleting/Cleaning all services needs a call to `ays destroy` and i skimmed through the available apis and it's not available.

**Comment by yveskerwyn** [comment]
So my understanding, do you need to fill out both fields in order to delete service?

**Comment by xmonader** [comment]
Yes.
