### ISSUE TITLE
Action menu on the Simulate page needs "consistency" update

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#107]
See screenshot

- Remove "go to shell" as it is not yet developed
- "Reload all Services" - "Reload all services" (moving the second uppercase for consistency)
- "init" -> "Init" (use uppercase for consistency)
- "install" -> "Install" 
- "Execute Action" -> "Execute action"
- "commit" -> "Commit" 

![screen shot 2016-07-19 at 11 10 09](https://cloud.githubusercontent.com/assets/13795109/16944570/866c1ada-4da1-11e6-9827-d6dcf8b8c033.png)

**Comment by zaibon** [comment]
fix in https://github.com/Jumpscale/jscockpit/commit/d93d6fbc77ed77bd6fa11b2a05fb0b2cd04c9f93

**Comment by yveskerwyn** [comment]
@zaibon thanks for checking #107 again since your fix didn't make it to my update
