### ISSUE TITLE
Blueprint for creating VDC requires admin rights - by design?

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#110]
Below blueprint executes successfully... only if the "moehaha" user account has admin rights

If this is by design, then a reseller has full admin rights to the Cloud Broker Portal - which seems not what we want, right?

g8client__gig:
  g8.url: 'gig.demo.greenitglobe.com'
  g8.login: 'moehaha'
  g8.password: '****'
  g8.account: 'Account of Moehaha.com'

ovc_user__yves:
  g8.client.name: 'gig'
  username: 'yves'
  email: 'yves@vreegoebezig.be'
  provider: 'itsyouonline'

vdc__4real3:
  g8.client.name: 'gig'
  g8.location: 'du-conv-1'
  maxMemoryCapacity: 4
  maxVDiskCapacity: 20
  maxCPUCapacity: 4
  maxNASCapacity: 20
  maxArchiveCapacity: 20
  maxNetworkOptTransfer: 5
  maxNetworkPeerTransfer: 15
  maxNumPublicIP: 1
  ovc_user:
    - 'yves'

**Comment by yveskerwyn** [comment]
Today we discovered that you even need level 1, level 2, level 3

**Comment by yveskerwyn** [comment]
Relates to the issue @rkhamis filed in openvcloud https://github.com/0-complexity/openvcloud/issues/315

**Comment by zaibon** [comment]
How is this will be handled ? Is there anything to do on the cockpit side ? if not can you close please.

**Comment by yveskerwyn** [comment]
@rkhamis did we fix this?

**Comment by rkhamis** [comment]
This isn't from our side.
ovc should fix it.
Will close.
