### ISSUE TITLE
Make the Actions menu on the Repository page more consistent

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#113]
See screenshot

"Reload All Services" -> "Reload all services"

So only the first word would be uppercase

![screen shot 2016-07-20 at 11 48 19](https://cloud.githubusercontent.com/assets/13795109/16982423/f2ce096c-4e6f-11e6-97f0-06f9b85bc613.png)

**Comment by xmonader** [comment]
I've just committed a fix to it.
