### ISSUE TITLE
Error when delete a service from a repo

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#114]
**Sequence**
- Create a repo
- Add blueprint
- Execute this blueprint
- choose "Delete service" from the drop down menu
- Press "Confirm" without enter the role or the service

**Actual Result**
![screenshot from 2016-07-20 12-04-46](https://cloud.githubusercontent.com/assets/17981089/16982804/9fb5f676-4e7a-11e6-99d5-322b3b79e524.png)

**Comment by xmonader** [comment]
Fields are required now.
