### ISSUE TITLE
Can't delete a service from the repo

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#115]
**Steps:**
- Create a repo
- Add blueprint
- Execute this blueprint
- choose "Delete service" from the drop down menu
- Enter the service Role name and the Sevice

**Actual Result**
![screenshot from 2016-07-20 12-16-07](https://cloud.githubusercontent.com/assets/17981089/16983204/63753422-4e7c-11e6-8ab8-da5732510fc3.png)

**Blueprint**
`g8client__dubai:
  g8.url: 'du-conv-2.demo.greenitglobe.com'
  g8.login: 'gig'
  g8.password: 'KrOe6gE9K5nCQdmretfXnj'
  g8.account: 'gig'

vdc__checkdeleteissue:
  g8.client.name: 'dubai'
  maxMemoryCapacity: 2
  maxVDiskCapacity: 10
  maxCPUCapacity: 2
  maxNASCapacity: 20
  maxArchiveCapacity: 20
  maxNetworkOptTransfer: 5
  maxNetworkPeerTransfer: 15
  maxNumPublicIP: 1`

**Comment by yveskerwyn** [comment]
Same here on Moehaha Cockpit

**Comment by zaibon** [comment]
duplicate https://github.com/Jumpscale/jscockpit/issues/127
