### ISSUE TITLE
cockpit Crashed cos of expired JWT session

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#116]
**Description**
When the session time is expired, Cockpit asks to re-login using the itsyou.online account. The JWT session has an error even if the user re-login many times and all repo are having the following error messages

![screenshot from 2016-07-20 12-51-42](https://cloud.githubusercontent.com/assets/17981089/16984270/af4a8dd4-4e81-11e6-8cb2-1143375da3e5.png)

**Comment by yveskerwyn** [comment]
Exactly the same here on the Moehaha Cockpit: https://moehaha.barcelona.aydo.com/cockpit/Repos

**Comment by zaibon** [comment]
finally found the problem. fixed in https://github.com/Jumpscale/jumpscale_core8/commit/d64ee52177d649d092c2d20527950651f51ee6a6
