### ISSUE TITLE
Update breadcrumb

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#124]
When navigating to a specific repository, the breadcrumb always looks like: "Cockpit Portal / Repos / Repo" (first screenshot)

Please change to:
"Cockpit Portal / **Repositories** / **Repository: %name-of-the-repo%**

So, two things:
- Don't use the abbreviations "repos" and "repo", and use "repositories" and "repository" instead
- Include the name of the repository in breadcrumb; as we do for instance in the **Cloud Broker Portal** for the  **Cloud Space Details** page (second screenshot)

<img width="878" alt="screen shot 2016-07-20 at 20 31 48" src="https://cloud.githubusercontent.com/assets/13795109/16998290/10808fae-4eb9-11e6-924d-a76ef28d0483.png">

<img width="556" alt="screen shot 2016-07-20 at 20 36 48" src="https://cloud.githubusercontent.com/assets/13795109/16998448/bd054378-4eb9-11e6-871c-0ad24cb7eee9.png">

**Comment by yveskerwyn** [comment]
Why was this closed?

Please update the breadcrumb as requested:

"Cockpit Portal / Repositories / Repository: %name-of-the-repo%"

Consistent with what we do in the Cloud Broker Portal, see screenshot in the original request

**Comment by xmonader** [comment]
https://github.com/Jumpscale/portal9/commit/adb4774556709be90a9cd0f8380a60d97b31a5fa
