### ISSUE TITLE
Add "Delete service" action on Instance Details page 

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#126]
On the **Instance Details** page there is no **Actions** menu and/or an action/button/link to Delete the service, see screenshot

Please add to action

<img width="1085" alt="screen shot 2016-07-20 at 21 33 01" src="https://cloud.githubusercontent.com/assets/13795109/17000184/a1fe234e-4ec1-11e6-84d3-d0edd6173107.png">

**Comment by zaibon** [comment]
fixed in https://github.com/Jumpscale/jscockpit/commit/4585034165f3a353e0b3addcc05342fbf094dcb7
