### ISSUE TITLE
Error when trying to delete a service

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#127]
Context, see the "nastest1" repository on the Moehaha Cockpit: https://moehaha.barcelona.aydo.com/cockpit/Repo?repo=nastest1

When trying to delete vm1 get the error shown in the screenshot:

<img width="627" alt="screen shot 2016-07-20 at 21 39 26" src="https://cloud.githubusercontent.com/assets/13795109/17000362/7937af74-4ec2-11e6-9b55-d5676e8d0671.png">

**Comment by zaibon** [comment]
A delete tries to do an uninstall then it deletes the service instance file.
The problem comes from AYS itself. If a service has not been properly installed in the first place when trying to do the uninstall action, most of the time the action will fail too and show the error like the one here.

**Comment by yveskerwyn** [comment]
Good that we understand what is wrong...

But we really need the "Delete" action to work even if the installation failed.

I filed a feature request for this: #142

**Comment by zaibon** [comment]
OK. I'll expose the ays destroy command in the portal so we can clean a repo even if some services are faulty.

**Comment by yveskerwyn** [comment]
@zaibon is this something you can fix today? I really need to clean-up the demo environment, and don't want to delete all repositories
