### ISSUE TITLE
Add Install action to Instance details page

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#129]
Currently there is no **Actions** menu and/or action to install a service on the Instance Details page; see screen shot

It would be convenient to have this in an Actions menu, together with the other actions such uninstall, delete, ...

<img width="783" alt="screen shot 2016-07-20 at 22 04 54" src="https://cloud.githubusercontent.com/assets/13795109/17001122/0d70120a-4ec6-11e6-8cf0-23e60d2df421.png">

**Comment by zaibon** [comment]
fixed in https://github.com/Jumpscale/jscockpit/commit/4585034165f3a353e0b3addcc05342fbf094dcb7
