### ISSUE TITLE
Missing AYS service template: blockdevice.raid

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#131]
When executing the blueprint on nastest4:
https://moehaha.barcelona.aydo.com/cockpit/repo?repo=nastest4

In general, what should I do in case a template is missing?

![screen shot 2016-07-21 at 10 25 38](https://cloud.githubusercontent.com/assets/13795109/17016060/81f34022-4f2d-11e6-9899-4e0f90b41c08.png)

**Comment by xmonader** [comment]
I don't think it's bundled by default:
https://github.com/Jumpscale/ays_g8_nas
You need to have it in your repository. you need to have those servicetemplates " https://github.com/Jumpscale/ays_g8_nas/tree/master/servicetemplates " in your servicetemplates directory

**Comment by yveskerwyn** [comment]
thanks @xmonader 

So that means that I'd need the broken functionality as reported here #132?

(for demo purposes I do not want add the template at the CLI)

Is this something you can fix and/or do you need the help of @zaibon?

**Comment by xmonader** [comment]
It's a design decision. of course I can add it to ays_jumpscale repo, but that decision is taken by @rkhamis or @zaibon 

Maybe I can add it locally to your system?

**Comment by zaibon** [comment]
This is indeed by design. We try now to have different repository for different service template so the templates can have there own live and we can create bug and versioning on them.
If you want to use it in your cockpit, you need to make sure you added this repository to the list of template repository first.

**Comment by yveskerwyn** [comment]
Adding this template to my repository requires CLI?

We also need a way to add templates using the Cockpit Portal I guess...

**Comment by zaibon** [comment]
fix in https://github.com/Jumpscale/jscockpit/commit/c5e56fd5eb650fe74ab801af95c9b21e2d399ab3
