### ISSUE TITLE
Template Details page only shows errors

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#132]
When navigating from the Templates page (first screenshot) to the Template Details page by clicking one of the webserver.caddy link, you only see errors (second screenshot).

![screen shot 2016-07-21 at 10 29 06](https://cloud.githubusercontent.com/assets/13795109/17016181/3161f1fc-4f2e-11e6-8198-3da7a11e135c.png)

![screen shot 2016-07-21 at 10 29 19](https://cloud.githubusercontent.com/assets/13795109/17016169/1a8fc080-4f2e-11e6-8905-777f233b9488.png)

**Comment by xmonader** [comment]
Fixed.

**Comment by xmonader** [comment]
Fixed
