### ISSUE TITLE
Templates page not showing any templates

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#133]
On the Templates page you don't see any templates, only a list with repositories and webserver.caddy links, see screenshot

What is the purpose of
- this Template page?
- the webserver.caddy links?

![screen shot 2016-07-21 at 10 29 06](https://cloud.githubusercontent.com/assets/13795109/17016263/9e217ba0-4f2e-11e6-8707-e81ae985fb9b.png)

**Comment by xmonader** [comment]
Fixed.

**Comment by yveskerwyn** [comment]
Could not verify since new bug #137
