### ISSUE TITLE
create python client for it

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#14]
- using the goraml
- put in jumpscale or create pip3... & jumpscale lib on top
- put also instructions in the jscockpit docs

**Comment by zaibon** [comment]
client added in :
https://github.com/Jumpscale/jscockpit/commit/ad7a510edbdb06b634e87453ce4c8ed2ef79d0de

The AYS API is protected by JWT. This client expect the user to provide the JWT.  
There is a helper method on the factory of the client to generate a JWT token. But creating a JWT requires a valid oauth token. Currently itsyou.online only support creation of oauth token using the API and requires a web server to receive the token.  
I created an issue at https://github.com/itsyouonline/identityserver/issues/91 to propose to add the ability to get an oauth token from the UI directly.

Until that, user need to get an oauth token by its own means to be able to use this client.

**Comment by zaibon** [comment]
refactored the jumpcale client : https://github.com/Jumpscale/jumpscale_core8/commit/f38da2772b9f99fb4a6cab889c68829953fc7364

It now has an upper layer specific for jumpscale and use the generated client from go-raml as backend, this allow to re-generate the client when raml specs change without modifying the public interface of the client.

**Comment by despiegk** [comment]
documentation will be created

**Comment by zaibon** [comment]
documentation  
commit : https://github.com/Jumpscale/jscockpit/commit/bfdb00e2aa00cb88da61518b73da69d730fc8342  
gitbook page : https://gig.gitbooks.io/cockpit/content/docs/jscockpit/api.html
