### ISSUE TITLE
Sorting on ID in Runs page doesn't work properly

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#141]
Two problems, both related to not handling IDs as numbers:

1. The number of items per page influences what you get to see:
- If only 10/page you don't get to see the most recent runs (with ID )  

![screen shot 2016-07-23 at 15 53 08](https://cloud.githubusercontent.com/assets/13795109/17078236/9e43fad4-50ed-11e6-9b38-c55507494426.png)

- If more than 10/page you still cannot get for instance run with ID 131 on top...

![screen shot 2016-07-23 at 15 56 03](https://cloud.githubusercontent.com/assets/13795109/17078255/ff2c2542-50ed-11e6-83d3-11c697d8d93c.png)

2. See how 9 is between 89 and 90, screenshot:

![screen shot 2016-07-23 at 15 49 06](https://cloud.githubusercontent.com/assets/13795109/17078209/1ef0b02e-50ed-11e6-8f8e-418994ba01f8.png)

**Comment by xmonader** [comment]
There's a problem due to the initialization of the Datatable. possible fix would be having the runids prefixed with zeros and sort it out as a string.

**Comment by rkhamis** [comment]
wouldn't that have been a nice fix to add to all datatables?
