### ISSUE TITLE
Failed installation of the sshkey service

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#143]
Steps:
- I started with a fresh repository created via a blueprint from Moehaha: https://moehaha.barcelona.aydo.com/cockpit/repo?repo=silke

- A first vm was added via the VDC Control Panel in Moehaha

- I added the below blueprint in the Cockpit portal in order to install a second vm to the VDC

- When executing the Install action on the repository things go wrong in step 2 with the sshkey service, halting installation:

![screen shot 2016-07-23 at 20 01 02](https://cloud.githubusercontent.com/assets/13795109/17079434/8c03365a-5110-11e6-9b18-c0144e0d0f83.png)

![screen shot 2016-07-23 at 20 01 26](https://cloud.githubusercontent.com/assets/13795109/17079436/91c1ee10-5110-11e6-8592-8ee6ffae9214.png)

**Comment by xmonader** [comment]
That was due to a very old my_init. I've updated it in the moehaha. Hopefully it'll work
