### ISSUE TITLE
API isn't working

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#145]
**Description**
I can't use any API from the API page and I noticed that all API are using the port 5000 to do its job
![screenshot from 2016-07-24 10-58-21](https://cloud.githubusercontent.com/assets/17981089/17082892/faed0228-5195-11e6-8b61-574aa8474cdd.png)
However when I checked the open ports I didn't find this port. The following screen present all open ports in moehaha cockpit
![screenshot from 2016-07-24 10-52-50](https://cloud.githubusercontent.com/assets/17981089/17082895/0ee110c6-5196-11e6-93f3-e9c250cbe001.png)

**Comment by zaibon** [comment]
Indeed the Raml specification needs to be updated during install to reflect the correct path of the cockpit.

**Comment by zaibon** [comment]
fixed in : https://github.com/Jumpscale/ays_jumpscale8/commit/3e578edfc257d8bb353f57793593f92fa6a9dd92
