### ISSUE TITLE
Wrong/no port forwardings are created when creating VM through blueprint

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#151]
Check the following blueprint:
<img width="1105" alt="screen shot 2016-07-24 at 17 22 22" src="https://cloud.githubusercontent.com/assets/13795109/17084640/41f85514-51c3-11e6-8539-757ff23aeaea.png">

No port forwarding were created:

<img width="1229" alt="screen shot 2016-07-24 at 17 24 38" src="https://cloud.githubusercontent.com/assets/13795109/17084659/bf978490-51c3-11e6-98ce-e05682a9354d.png">

On the other hand, somehow following port forwarding were created for another VM I created via a blueprint, see https://gig.demo.greenitglobe.com/CBGrid/Cloud%20Space?id=71

<img width="1158" alt="screen shot 2016-07-24 at 17 28 23" src="https://cloud.githubusercontent.com/assets/13795109/17084665/0ea2b6fe-51c4-11e6-9e3f-1a02c0af0abd.png">

**Comment by yveskerwyn** [comment]
@islamTaha12 thanks for adding your findings on this

**Comment by zaibon** [comment]
not related to cockpit. this issue should be create for the node.ovc service in https://github.com/Jumpscale/ays_jumpscale8

**Comment by zaibon** [comment]
fix in https://github.com/Jumpscale/ays_jumpscale8/pull/52
