### ISSUE TITLE
Chatbot doesn't report error to the user properly

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#152]
See chatbot conversation:

<img width="536" alt="screen shot 2016-07-24 at 17 35 16" src="https://cloud.githubusercontent.com/assets/13795109/17084700/1188c40c-51c5-11e6-8f01-79c0c8f99ab7.png">

Two problems:
1. The chatbot doesn't give any feedback about the successfull creation
2. The new blueprint doesn't show-up in the Cockpit:

<img width="1138" alt="screen shot 2016-07-24 at 17 37 47" src="https://cloud.githubusercontent.com/assets/13795109/17084719/667be0de-51c5-11e6-8849-c40968fe5145.png">

**Comment by yveskerwyn** [comment]
Just tried again - in order to be 100% sure:

See blueprint "vm4-of-silke": https://moehaha.barcelona.aydo.com/cockpit/cockpit/Blueprints?ayspath=silke

See result: https://gig.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1229

<img width="1362" alt="screen shot 2016-07-24 at 18 22 00" src="https://cloud.githubusercontent.com/assets/13795109/17084945/8c24fc2a-51cb-11e6-8da3-bbeecc08963e.png">

<img width="1204" alt="screen shot 2016-07-24 at 18 22 23" src="https://cloud.githubusercontent.com/assets/13795109/17084947/9af8aa08-51cb-11e6-9f14-e341e31f9f37.png">

**Comment by zaibon** [comment]
Can't reproduce.
I just create a new blueprint from the chatbot and the blueprint is avaiable in the portal.
Also the bot send a message once the blueprint is executed.
![2016-07-24_598x419_scrot](https://cloud.githubusercontent.com/assets/303164/17086444/5c8f4174-51f2-11e6-8366-e74b18c9fc88.png)

**Comment by yveskerwyn** [comment]
@zaibon can you try a blueprint that is a little more sophisticated?

I tried the following on the repository "dylanverstraete": https://moehaha.barcelona.aydo.com/cockpit/repo?repo=dylanverstraete

<img width="625" alt="screen shot 2016-07-25 at 09 22 17" src="https://cloud.githubusercontent.com/assets/13795109/17093403/68d2645a-5249-11e6-8de6-7bf30703f4fa.png">

**Comment by yveskerwyn** [comment]
Executing the same blueprint on another repo worked, see first screenshot

Now it shows up in the Cockpit, see second screenshot

Still no/waiting for feedback from the chatbot though, first screenshot

<img width="612" alt="screen shot 2016-07-25 at 09 32 51" src="https://cloud.githubusercontent.com/assets/13795109/17093655/ceef45a4-524a-11e6-8a5f-129a6c3a293b.png">

![screen shot 2016-07-25 at 09 34 33](https://cloud.githubusercontent.com/assets/13795109/17093702/12f56c38-524b-11e6-9e09-7c22bac04424.png)

**Comment by yveskerwyn** [comment]
@zaibon see screenshots below for error details as shown in Runs

![screen shot 2016-07-25 at 09 38 24](https://cloud.githubusercontent.com/assets/13795109/17093793/a4804038-524b-11e6-9807-9a50594c1cd8.png)

![screen shot 2016-07-25 at 09 38 56](https://cloud.githubusercontent.com/assets/13795109/17093798/a96badd0-524b-11e6-8a55-7f7c80e09297.png)

**Comment by zaibon** [comment]
Only error related to cockpit is the chatbot not reporting error to the user. 
Other error relates to AYS itself
