### ISSUE TITLE
Some blueprints can't be archived

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#153]
Error when trying to archive blueprint "4-du":
https://moehaha.barcelona.aydo.com/cockpit/cockpit/Blueprints?ayspath=yves

<img width="1245" alt="screen shot 2016-07-24 at 18 13 37" src="https://cloud.githubusercontent.com/assets/13795109/17084909/68ae2be6-51ca-11e6-9801-662fd3207255.png">

**Comment by zaibon** [comment]
fixed in https://github.com/Jumpscale/jscockpit/commit/185d710fcbe573d0da6ce7009538370c3a4d2224
