### ISSUE TITLE
cockpit_portal: Still some blueprints that cannot be archived

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#155]
This is a blueprint that got added through the chatbot:

https://moehaha.barcelona.aydo.com/cockpit/cockpit/Blueprints?ayspath=silke

![screen shot 2016-07-25 at 10 16 37](https://cloud.githubusercontent.com/assets/13795109/17094623/e7977bca-5250-11e6-93cc-a9fceb295ef6.png)

**Comment by ashraffouda** [comment]
already fixed in the current version
