### ISSUE TITLE
cockpit_portal: Add possibility to update templates in the Cockpit Portal

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#160]

**Comment by abdulrahmantkhalifa** [comment]
by update u mean pull the ays repo , or to actually edit the code in the repo

**Comment by yveskerwyn** [comment]
@abdulrahmantkhalifa we need two things:

1. Ability to update the actor templates that are stored in /optvar/code/github/jumpscale/ays_jumpscale
2. Ability to update the actors as already in use in a specific Cockpit repository

The first can be achieved by connecting over SSH to the Cockpit VM and execute ```git pull``` in /optvar/code/github/jumpscale/ays_jumpscale

The second can be achieved by connecting over SSH to the Cockpit VM and execute ```ays update -n vdc``` (in case you only want to update the vdc actor)

So in case you want to update the actors for a specific cockpit repository you will need to do first a ```git pull```, followed by an ```ays update```, unless you just want to update the actor based on the actor templates as available in /optvar/code/github/jumpscale/ays_jumpscale

Both require ssh root access to the Cockpit VM, which is undesirable, having the same exposed in the Cockpit Portal is what we need. 

This would require a new feature in two places of the Cockpit Portal:
- First screenshot, here you see the global Actor Templates directory
  - at least (for now) we need a button/action here to update all actor templates, basically executing the above mentioned ```git pull```
  - later we also need an action/link to add new actor templates, allowing you to specify a repository...
  - later we also need a way to selectively update some of the templates
- Second screenshot, shows all templates as globally available (discussed above) + the local actor templates (/optvar/cockpit_repos/$cockpit-repository-name$/actorTemplates)
  - at least (for now) we need a button here to update all listed actor templates, basically updating the actors based on the templates available from /optvar/code/github/jumpscale/ays_jumpscale
  - in the future we need an action/link to add an actor template to the local (local to the repo) actor templates
  - ... 

![screen shot 2016-11-28 at 17 00 09](https://cloud.githubusercontent.com/assets/13795109/20675304/1ff22378-b58c-11e6-9ca6-47e786488125.png)

![screen shot 2016-11-28 at 17 00 33](https://cloud.githubusercontent.com/assets/13795109/20675327/2faed856-b58c-11e6-82c6-ef8a94211bbf.png)

**Comment by abdulrahmantkhalifa** [comment]
https://github.com/Jumpscale/jumpscale_core8/commit/da9bc57849f194e7d64b7239618adc3b190c69bd

**Comment by abdulrahmantkhalifa** [comment]
adjustments to new requirements are being made , not closed
