### ISSUE TITLE
Runs are not delete when you delete a repo

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#161]
As a result when recreating a new repo with the same name as the old repo, you get to see all the old ruins, see screenshot:

<img width="1188" alt="screen shot 2016-07-26 at 11 42 12" src="https://cloud.githubusercontent.com/assets/13795109/17133376/05e40550-5326-11e6-8459-2b80511cd65a.png">

**Comment by xmonader** [comment]
I believe it's fixed in this PR https://github.com/Jumpscale/jumpscale_core8/pull/448 (It's a jumpscale issue).
