### ISSUE TITLE
Blueprint not picked-up in the simulator

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#165]
https://moehaha.barcelona.aydo.com/cockpit/cockpit/Blueprints?ayspath=yves

When simulating the below nothing is done, also no errors...

![screen shot 2016-07-28 at 12 10 11](https://cloud.githubusercontent.com/assets/13795109/17209222/4b77a8d2-54bc-11e6-9abe-da3c6b39382f.png)

**Comment by zaibon** [comment]
Need more information. 
What action are you trying to simulate, current state of the service instances...

**Comment by yveskerwyn** [comment]
Too long agoo
