### ISSUE TITLE
When simulating with Force=True

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#166]
After simulation once with Force=True, there is no way to simulate again with Force=False - it is simply ignored that you require Force=False, as if when you set Force=True it changes something on the instances than can not reset - Reset doesn't help neigher.

**Comment by zaibon** [comment]
@yveskerwyn 
It's a bug in AYS itself not related to cockpit. please move issue to [core](https://github.com/Jumpscale/jumpscale_core8)
