### ISSUE TITLE
Generating server code from the raml file

### ISSUE THREAD

**Issue by DylanVerstraete** [Jumpscale/jscockpit#168]
when generating the server code, there is an issue in service.py

It generates :

actions.py = TextField(validators=[])
name = TextField(validators=[DataRequired(message="")])
schema.hrd = TextField(validators=[DataRequired(message="")])
service.hrd = FormField(object)

But it should be :

actions_py = TextField(validators=[])
name = TextField(validators=[DataRequired(message="")])
schema_hrd = TextField(validators=[DataRequired(message="")])
service_hrd = FormField(object)

**Comment by xmonader** [comment]
In jscockpit/ays_api/Template.py 
```


class Template(Form):

    actions_py = TextField(validators=[DataRequired(message="")])
    name = TextField(validators=[DataRequired(message="")])
    schema_hrd = TextField(validators=[DataRequired(message="")])
    service_hrd = FormField(object)
```
and 
jscockpit/ays_api/service.py
```

from flask_wtf import Form
from wtforms.validators import DataRequired, Length, Regexp, NumberRange, required
from wtforms import TextField, FormField, IntegerField, FloatField, FileField, BooleanField, DateField, FieldList
from .input_validators import multiple_of


class Service(Form):

    actions_py = TextField(validators=[DataRequired(message="")])
    instance = TextField(validators=[DataRequired(message="")])
    instance_hrd = TextField(validators=[DataRequired(message="")])
    name = TextField(validators=[DataRequired(message="")])
    state = TextField(validators=[DataRequired(message="")])

```

It looks good to me?

**Comment by DylanVerstraete** [comment]
Its like that when generated with go-raml , its a minor bug in the raml file
