### ISSUE TITLE
Update jscockpit and portal code to use new API of AYS.

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jscockpit#171]
Because of [this breaking change](https://github.com/Jumpscale/jumpscale_core8/commit/a4b93a4897c42be0d34db8c96f8591535e254dd2#diff-82ef5280c6d46644bba1d66e9b98ca05R279) in the AYS API, we need to go over all the code of jscockpit and portal to make sure the logic is updated.

**Comment by xmonader** [comment]
We are calling .repos directly which calls findAYSRepos without specifying a path. I think the default value should be /opt or never call the .repos property.

**Comment by zaibon** [comment]
I will refactor the code so we don't use j.atyoureservice.repos and instead always specify a path that is specific for the cockpit use case.
