### ISSUE TITLE
can't install a bp from the portal however its installed well using ays commands

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#172]
**Description**
I can't install the following blueprint using the install command in the repo

> g8client__test:
>   g8.url: 'gig.demo.greenitglobe.com'
>   g8.login: 'gig'
>   g8.password: 'KrOe6gE9K5nCQdmretfXnj'
>   g8.account: 'gig'
> 
> vdc__helloislam4:
>   g8.client.name: 'test'              
>   g8.location : 'du-conv-1'
>   maxMemoryCapacity: 2
>   maxVDiskCapacity: -1
>   maxCPUCapacity: -1
>   maxNASCapacity: 20
>   maxArchiveCapacity: 20
>   maxNetworkOptTransfer: 5
>   maxNetworkPeerTransfer: 15
>   maxNumPublicIP: 1

This error is producing :
by @rkhamis 
> ERROR: Cannot get ays service 'os!centrilogic', did not find ((type:input.error  cat:1)

However I can install from the docker machine using the ays install commands

**Secnario**
From the portal:
- Add a new bp to the repo (bp to create a cloud space)
- Execute this bp
- Install this bp 
- Check the service state on the instance of the repo.

**Cockpit portal**
https://centrilogic.aydo2.com

**Comment by zaibon** [comment]
This looks like another blueprint has not been properly deployed before in the same repo.
Cause in the blueprint pasted here I don't see any `os` service. So if AYS complains about the missing  `os!centrilogic` a bad manipulation has been done before.
