### ISSUE TITLE
Chatbot doesn't react anymore when clicking the Select button

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#177]
![screen shot 2016-08-09 at 12 07 17](https://cloud.githubusercontent.com/assets/13795109/17513087/3d304e5a-5e2b-11e6-9c5f-afd9924f8ad5.png)

After clicking "Select":
![screen shot 2016-08-09 at 12 19 00](https://cloud.githubusercontent.com/assets/13795109/17513124/7c1f1498-5e2b-11e6-8e77-56a464c29f43.png)

**Comment by zaibon** [comment]
fixed in https://github.com/Jumpscale/jscockpit/commit/de8e9c271982d7a9cf2e609ae15bff9d53de4535
