### ISSUE TITLE
Moehaha Cockpit broken with strange error

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#178]
When creating fresh/new repository and loading below blueprint getting strange error:
https://moehaha.barcelona.aydo.com/cockpit/action?runid=ays_Test&actionkey=actions.install.__GUARD__

![screen shot 2016-08-09 at 12 20 03](https://cloud.githubusercontent.com/assets/13795109/17513179/d2ebeb98-5e2b-11e6-8698-b62a63fd9245.png)

g8client__gig:
  g8.url: 'gig.demo.greenitglobe.com'
  g8.login: 'moehaha2'
  g8.password: '***'
  g8.account: 'Account of Moehaha.com'

ovc_user__yves:
  g8.client.name: 'gig'
  username: 'yves'
  email: 'yves@vreegoebezig.be'
  provider: 'itsyouonline'

vdc__vdc4test:
  g8.client.name: 'gig'
  g8.location: ' be-scale-2'
  maxMemoryCapacity: 4
  maxVDiskCapacity: 20
  maxCPUCapacity: 4
  maxNASCapacity: 20
  maxArchiveCapacity: 20
  maxNetworkOptTransfer: 5
  maxNetworkPeerTransfer: 15
  maxNumPublicIP: 1
  ovc_user:
    - 'yves'

**Comment by zaibon** [comment]
fixed in https://github.com/Jumpscale/jscockpit/commit/3af0e187cf15482809e6f37854445543c6a28111
