### ISSUE TITLE
cockpit create an extrea blue print

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#182]
**Steps**

> I added the following blue print. 
> g8client__cockpittest:
>   g8.url: 'be-g8-3.demo.greenitglobe.com'
>   g8.login: 'gig'
>   g8.password: 'KrOe6gE9K5nCQdmretfXnj'
>   g8.account: 'gig'
> 
> vdc__helloislam:
>   g8.client.name: 'cockpittest'  
>   maxMemoryCapacity: 2
>   maxVDiskCapacity: 10
>   maxCPUCapacity: 2
>   maxNASCapacity: 20
>   maxArchiveCapacity: 20
>   maxNetworkOptTransfer: 5
>   maxNetworkPeerTransfer: 15
>   maxNumPublicIP: 1
> 
> node.ovc__vmislam1:
>     os.image: 'ubuntu 16.04 x64'
>     disk.size: 10
>     datadisks:
>         - 'name:disk1 size:50 type:normal'
>         - 'name:disk2 size:50 type:normal'
>     os.size: 2
>     ports:
>         - '139:139'
>         - '445:445'
>         - '137:137'
>         - '138:138'
> vdc: 'helloislam'
- press on "Execute the blueprint" 
- press on "init"
- press on "Execute the blueprint" again
- Check the blueprints
  ![screenshot from 2016-08-18 14-36-26](https://cloud.githubusercontent.com/assets/17981089/17774047/389b2820-655a-11e6-86ad-efe499113323.png)
- Explore the blueprints
  ![screenshot from 2016-08-18 14-36-07](https://cloud.githubusercontent.com/assets/17981089/17774054/44257092-655a-11e6-93e7-a23d24930f5e.png)

**Actual result**
There is an extra blueprint.

**cockpit url**
https://moehaha.barcelona.aydo.com

**software version**

JumpScale

```
Core: HEAD
Portal: master
```

JSCockpit

```
Core: master
```

**Comment by zaibon** [comment]
How did you add the blueprint to the cockpit ?

**Comment by zaibon** [comment]
@islamTaha12 
Didn't managed to reproduce.
Can you confirm if you still have the issue ?
