### ISSUE TITLE
all pop-ups aren't responce to the "Enter" press from the keyboard

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#184]
**Steps**
- Press on "Add repository"
- Enter the repo name
- Press "Enter" 

**Actual Result**
The pop-up will be disappeared without creating the repo

**Expected Result**
The new Repo should be added and this repo should response to the "Eneter" keyboard button.

**Comment by zaibon** [comment]
Not related with cockpit but with portal itself. please move error to https://github.com/Jumpscale/jumpscale_portal8
