### ISSUE TITLE
cockpit log me out when using ays commands in the cockpit machine 

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#186]
**Steps**
- Login the cockpit using the itsyou.online 
- Connect to the cockpit vm through the ssh command
- Execute the AYS commands to install any blue print 
- Check the portal of the cockpit 

**Actual Result**
The cockpit logged me out and I have to login again using the itsyou.online

**Comment by rkhamis** [comment]
Are you sure your session didn't just expire?

**Comment by zaibon** [comment]
Like @rkhamis said, your session just expire at the same time you were doing the action on the vm.
There is not relation between AYS command and session of the portal.
The session on the cockpit is has long has the oauth token from itsyou.online so 24h.
