### ISSUE TITLE
cockpit version isn't correct

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#187]
**Description**
The cockpit software version isn't updated and it contains the following info for all repo.
![screenshot from 2016-08-22 11-52-49](https://cloud.githubusercontent.com/assets/17981089/17850750/58ef060e-6867-11e6-9505-9a99c5eadf52.png)

**Comment by rkhamis** [comment]
It says which branches it's installed with.
Currently, we don't have versions tagged, so this is as specific as it can get
