### ISSUE TITLE
Can't execute the blueprints without "init" at first

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#188]
**Description**
I added a blueprint to the repo and I pressed on "Execute blueprint". When I checked the "recipes" and the "services" folders, I didn't find it. So I pressed on "init" and re-pressed "Execute blueprints". now, I can find the "recipes" and the "services" folders, and I went to init then install steps.

**Comment by zaibon** [comment]
How did you add the blueprint to the cockpit ?
Does the blueprint was visible in the Blueprint page before doing the `execute blueprint` action ?
