### ISSUE TITLE
Repeating error message in Chatbot

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#199]
Checked with @moehaha-chatbot 

This message continuously comes back: "Error happened on action monitor on service os instance moehaha-cockpit in repo ays_cockpit: 'ays_cockpit'" - see screenshot

<img width="1323" alt="screen shot 2016-09-19 at 15 51 21" src="https://cloud.githubusercontent.com/assets/13795109/18634403/0d9a4fa8-7e81-11e6-8956-e834cc2732d3.png">

**Comment by zaibon** [comment]
has long as the error is not fix it should keep notifying the user of the error
