### ISSUE TITLE
Install Scripts

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jscockpit#2]
See https://github.com/0-complexity/g8cockpit/blob/master/specs/install_cockpit.md#install-script

**Comment by despiegk** [comment]
moved? can't find

**Comment by despiegk** [comment]
should not be in 0-complexity
js users should be able to deploy a cockpit

**Comment by zaibon** [comment]
Now there is a blueprint to deploy a cockpit so no more install script is needed.
I'll explain how to use the blueprint while I'm updating the documentation.

**Comment by zaibon** [comment]
see https://gig.gitbooks.io/cockpit/content/docs/jscockpit/installation.html
