### ISSUE TITLE
"502 Bad Gateway" error when updating Moehaha Cockpit

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#201]
https://moehaha-cockpit.aydo2.com/cockpit/version

<img width="1220" alt="screen shot 2016-09-20 at 12 08 02" src="https://cloud.githubusercontent.com/assets/13795109/18666237/05459cfe-7f2b-11e6-8b18-a1a3e8df1d62.png">

**Comment by zaibon** [comment]
duplicate from #139
