### ISSUE TITLE
How can I delete a user?

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#205]
@zaibon 

Once I've created an ovc_user instance, I should be able to fetch a list of available actions for that ovc_user instance (there is a Cockpit API for that), I don't see however any Cockpit API for executing an action... right? Or maybe it's done through an action, but rather a Cockpit API te delete a service instance, but then again I don't see an API in the API Console...

Or am I searching in the wrong place? Is there another way to delete a user?

**Comment by zaibon** [comment]
To execute action on services you have to go to the repository and click on `Execute action`
![2016-09-21_249x210_scrot](https://cloud.githubusercontent.com/assets/303164/18699369/548018fc-7fd1-11e6-8fe7-e2aa34dc6021.png)

This will show you a form where you can specify which action you want to execute.

**Comment by yveskerwyn** [comment]
Thanks @zaibon , but where can I find the API to execute an action on a service in the API Console?

<img width="1262" alt="screen shot 2016-09-21 at 09 42 48" src="https://cloud.githubusercontent.com/assets/13795109/18701965/d5501cb2-7fdf-11e6-8a7b-f98076709d50.png">


I only see the API for listing all Actions for a certain service instance - see screenshot:

<img width="1255" alt="screen shot 2016-09-21 at 09 36 31" src="https://cloud.githubusercontent.com/assets/13795109/18701913/8e72ea5e-7fdf-11e6-8645-fa83d69089cc.png">

**Comment by zaibon** [comment]
![2016-09-21_762x224_scrot](https://cloud.githubusercontent.com/assets/303164/18702492/4d672446-7fe2-11e6-9df1-839642d38fe3.png)
