### ISSUE TITLE
API Console > List actions for a service instance doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#206]
as discussed w/ @zaibon 

the URI parameters get wrongly passed -  see screenshot:

<img width="1255" alt="screen shot 2016-09-21 at 09 36 31" src="https://cloud.githubusercontent.com/assets/13795109/18702059/36cd8f4c-7fe0-11e6-988f-0500a59f11d4.png">

**Comment by zaibon** [comment]
this is not a problem with argument, Problem is during installation base uri of the raml file used by the API console is not set problerly. Need to check why this line is not execued properly : https://github.com/Jumpscale/ays_jumpscale8/blob/master/_os/os.cockpit/actions.py#L245
