### ISSUE TITLE
Executing the "uninstall" action on an ovc_user instance doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#207]
Tested on artililiumv2.aydo2.com/cockpit

<img width="595" alt="screen shot 2016-09-21 at 11 18 49" src="https://cloud.githubusercontent.com/assets/13795109/18705544/f6228d4e-7fee-11e6-91cd-7053979e25e1.png">

Once done, nothing happened:

<img width="1120" alt="screen shot 2016-09-21 at 11 33 35" src="https://cloud.githubusercontent.com/assets/13795109/18705647/4d01fb40-7fef-11e6-8c6c-38e4026f7bc0.png">

<img width="1139" alt="screen shot 2016-09-21 at 11 33 50" src="https://cloud.githubusercontent.com/assets/13795109/18705660/54c386be-7fef-11e6-8385-3e9fc833f60b.png">

<img width="1068" alt="screen shot 2016-09-21 at 11 34 50" src="https://cloud.githubusercontent.com/assets/13795109/18705689/75a93644-7fef-11e6-8c82-75d00ca46cc8.png">

**Comment by yveskerwyn** [comment]
Also when going through the API Console same result: nothing, only message that "uninstall is scheduled":

<img width="351" alt="screen shot 2016-09-21 at 15 04 06" src="https://cloud.githubusercontent.com/assets/13795109/18712074/0bc25e5e-800d-11e6-88d0-bfc482ab6981.png">

**Comment by zaibon** [comment]
Need to validate the service behave properly and then test from the cockpit.
If the issue come from the service implementation, this issue need to be moved to https://github.com/Jumpscale/ays_jumpscale8
