### ISSUE TITLE
cockpit_portal: Wrong message when successfully initializing a blueprint

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#211]
When initializing/executing a specific blueprint, e.g.:
https://moehaha-cockpit.aydo2.com/api/ays/repository/test-repo6/blueprint/test-vdc-artilium-dev.yaml

Response is:
{
  "msg": "Blueprint test-repo6 initialized"
}

While response should be:
{
  "msg": "Blueprint test-vdc-artilium-dev.yaml initialized"
}

**Comment by ashraffouda** [comment]
can not reproduce
