### ISSUE TITLE
Cockpit API for getting repository details doesn't return git_url

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#220]
![screen shot 2016-11-07 at 14 54 36](https://cloud.githubusercontent.com/assets/13795109/20060188/37f2c6a0-a4fa-11e6-9c06-36797ed8ef33.png)

**Comment by rkhamis** [comment]
https://github.com/Jumpscale/jscockpit/commit/9fd76e19e0089830b69e0e70e2d47a761679beb1
