### ISSUE TITLE
object has no attribute 'items' error when executing g8client blueprint

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#221]
Blueprint:

g8client__uk:\n  g8.url: uk-g8-1.demo.greenitglobe.com\n  g8.login: yves\n  g8.password: ****\n  g8.account: Account of Yves

Same if I drop the "g8." prefix:

g8client__uk:\n url: uk-g8-1.demo.greenitglobe.com\n login: yves\n password: ****\n account: Account of Yves

**Comment by zaibon** [comment]
Error comes from the new format of config used in JumpScale now.
This is fixed on master  by :https://github.com/Jumpscale/jumpscale_core8/commit/c7c774ecc7c78a746a0c606dc477d609abc6f7da

But not in the sandbox yet. the sandbox need to be updated and reviewed to make sure it works with the new configuration system
