### ISSUE TITLE
Cockpit accepts non-valid blueprints

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#223]
Currently it is possible to use the /ays/repository/{repository}/blueprint API to feed the Cockpit with invalid blueprints, as show in the screenshot below.

Invalid blueprints should not be accepted, at least YAML validation is needed, and extra validation against some other, more specific, rules is more than desirable to avoid support issues going forward.

![screen shot 2016-11-08 at 10 44 50](https://cloud.githubusercontent.com/assets/13795109/20095680/c200ca20-a5a6-11e6-8cfa-d1011f1a42a7.png)

**Comment by rkhamis** [comment]
We can start by validating yaml syntax.
To check if the blueprint logic is acceptable to AYS, I guess we can simulate a run, see if it complains then destroy that run.

What do you think, @zaibon ?

**Comment by rkhamis** [comment]
Fixed in https://github.com/Jumpscale/jscockpit/commit/519e81a43b4eb70e20462ecfe4a97bcabe6dcc39
