### ISSUE TITLE
Delete service in Cockpit doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#225]
Tested in https://cl.aydo2.com/ays81/ays81/Services?ayspath=/optvar/cockpit_repos/yves2

When clicking **Delete** in Actions column nothing happens:

![screen shot 2016-11-08 at 13 49 06](https://cloud.githubusercontent.com/assets/13795109/20099714/5103c048-a5ba-11e6-8c6c-222e0623dc03.png)

**Comment by xmonader** [comment]
Fixed
