### ISSUE TITLE
Unable to install Cockpit using ays

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#228]
On my local machine (mac), with an up to date js8 (master), and having first prepared a valid cockpit.yaml, I get this:

```bash
ays blueprint

**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 333, in <module>
    cli()
  File "/usr/local/bin/ays", line 101, in blueprint
    atyourservice.execute_blueprint(role=role, instance=instance, path=path)
  File "/usr/local/lib/python3.5/site-packages/JumpScale/baselib/atyourservice/AtYourServiceRepo.py", line 267, in execute_blueprint
    bp.load(role=role, instance=instance)
  File "/usr/local/lib/python3.5/site-packages/JumpScale/baselib/atyourservice/Blueprint.py", line 86, in load
    recipe = self.aysrepo.getRecipe(aystemplate_name)  # will load recipe if it doesn't exist yet
  File "/usr/local/lib/python3.5/site-packages/JumpScale/baselib/atyourservice/AtYourServiceRepo.py", line 640, in getRecipe
    template = self.getTemplate(name=name, die=die)
  File "/usr/local/lib/python3.5/site-packages/JumpScale/baselib/atyourservice/AtYourServiceRepo.py", line 623, in getTemplate
    raise j.exceptions.Input("Cannot find template with name:%s" % name)
OurExceptions.Input: ERROR: Cannot find template with name:g8client ((type:input.error)


***ERROR***
  type/level: input.error/1
Cannot find template with name:g8client
```

**Comment by xmonader** [comment]
you need to have `.ays` file in your repository directory
also It should be (a valid git repo) -- (run `git init`)
also It needs to have remote: so go to your github account and create a remote repo and execute the following from your ays repo directory
`git remote add origin https://github.com/USERNAME/REMOTEREPO.git` after replacing username with your github username and remoterepo with your remote repo

**Comment by yveskerwyn** [comment]
yes the .ays problem I fixed, let me fix the rest

**Comment by yveskerwyn** [comment]
trying to understand the error message, "Cannot find template with name:g8client", I can only confirm that the g8client **schema.hrd** and g8client **actions.py** are in the up to date (origin/js81) directory /Users/yves/Documents/GitHub/JumpScale/ays_jumpscale8/clients/g8client

Not sure where/how the code searches for the g8client template?

What else can I check?

**Comment by yveskerwyn** [comment]
I just discover that I also still have jumpscale_core8 directory in ~/opt/code/github/jumpscale, while I've been using in /Users/yves/Documents/GitHub/JumpScale for most of my work, that could be the problem? Sorry for my ignorance...

**Comment by rkhamis** [comment]
Is this still an issue we need to look into? Or is fixed with a clean installation?

**Comment by yveskerwyn** [comment]
this still an issue yes, can't get it right on my mac machine

**Comment by abdulrahmantkhalifa** [comment]
should be fixed , update jumpscale_core8 repo and ays_jumpscale8 repo , and it should work
