### ISSUE TITLE
Runs page in repo shows all runs, not just the runs for the repo

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#230]
See breadcrumb: I'm in repo yves3, for which no runs occurred yet
While the page shows all runs

![screen shot 2016-11-09 at 12 09 59](https://cloud.githubusercontent.com/assets/13795109/20136518/91be083a-a675-11e6-847f-dd5a68ebd1dd.png)

**Comment by yveskerwyn** [comment]
Feedback from @zaibon:

the problem is
that the runs page
show all the runs
from all repos
that is cause technically a runs is not related to AYS at all
it's just a piece of work
so we need to fix this in the portal
so we can't access runs from other repos

**Comment by rkhamis** [comment]
Turns out the run model has no information about the repo model and vice versa.

**Comment by rkhamis** [comment]
Fixed in https://github.com/Jumpscale/jumpscale_core8/commit/2bc90438436fb43f01c8e5e40b842293b01ba2cf
