### ISSUE TITLE
cockpit_portal: Can't create repo without enter a git link and there is no error message

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#231]
**Steps**
- Access the repository page 
- Press on the "create repository" button
- Enter the repo name and leave the github link empty
- Press confirm
![screenshot from 2016-11-09 16-19-20](https://cloud.githubusercontent.com/assets/17981089/20141285/490c3cc4-a698-11e6-8d78-84f034faf8ae.png)

**Actual result**
- There is no error message and the repo wasn't created too.

**Comment by abdulrahmantkhalifa** [comment]
fixed in https://github.com/Jumpscale/jumpscale_portal8/commit/db2cbcfb7afeb158ce1d70ff24a7e57ec0b0e16f
