### ISSUE TITLE
Blueprint page is empty

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#232]
**Steps:**
- Create a new repo
- Access the Bp

**Actual result**
![screenshot from 2016-11-09 16-22-09](https://cloud.githubusercontent.com/assets/17981089/20141377/c1102c30-a698-11e6-9661-ae56801102b4.png)

**Comment by rkhamis** [comment]
Do you actually have blueprints defined?

**Comment by islamTaha12** [comment]
No I don't have bp. I just created a new repo. In case of the bp page will be empty, may be a hint message will be better than the empty page
