### ISSUE TITLE
cockpit_portal: "Internal error" when run the blueprint from the api

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#234]
**Steps**
- Create a repo.
- Create a blueprint from the API
- Try to run this blueprint using the post /ays/repository/{repository}/blueprint/{blueprint}

**Actual result**
![screenshot from 2016-11-09 16-33-49](https://cloud.githubusercontent.com/assets/17981089/20141795/9e1c1c82-a69a-11e6-9bd7-c9ca6eab4050.png)

**Comment by zaibon** [comment]
Can be have the blueprint that triggers the error past here

**Comment by ashraffouda** [comment]
after discussing this with @islamTaha12  he said this was  the behavior for any bp even if the bp is correct and can execute it from AYS.
this can not be reproduced
