### ISSUE TITLE
cockpit_portal: Jwt token text isn't appear corrent in the pop-up

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#235]
**Steps**
- From firefox, get https://cockpit1.aydo2.com/ays81/jwt
- Generate a jwt 
- Copy it and paste it in any editor 
- Compare between the pop-up and the actual result

**Actual result**
![screenshot from 2016-11-09 16-59-42](https://cloud.githubusercontent.com/assets/17981089/20142631/43f61876-a69e-11e6-8dd5-9ba4b4c98520.png)

while the jwt is :
eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicXVhbGl0eV9jb2NrcGl0XyIsInF1YWxpdHlfY29ja3BpdF8iXSwiZXhwIjoxNDc4NzgxMzM3LCJpc3MiOiJpdHN5b3VvbmxpbmUiLCJzY29wZSI6InVzZXI6bWVtYmVyb2Y6cXVhbGl0eV9jb2NrcGl0XyIsInVzZXJuYW1lIjoiaXNsYW10ZXN0In0.grn054vzSG_yrcj_ImtsEWGZKiIMfbqfpPUIrcjqgfmgeVxWCJgcjLx00098Y8KKhCZPTHwfgY5cpPFayDE6AJGcjASolhwpDuEwXRxPrvM_QcUm3DotRCvyAdOdmPZ2

**Comment by ashraffouda** [comment]
this does not exist anymore 
![screenshot from 2016-11-27 14-48-24](https://cloud.githubusercontent.com/assets/1689456/20648474/b40f07e2-b4b0-11e6-90e5-097f0cb07651.png)
