### ISSUE TITLE
cockpit_portal: Move template repo out of the fuse mountpoint.

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jscockpit#236]
Currently the cockpit us powered by https://github.com/g8os/fs. 
The mount point used is `/opt`.  The issue is that the default actor Templates repo which is https://github.com/Jumpscale/ays_jumpscale8 is downloaded in `/opt/code/github/jumpscale/ays_jumpscale8` 

The fuse doesn't deal well with git workflow and this may cause some corruption of the file.

We need a way to move these templates repositories out of the fuse mount point  or improve the fuse so it's fully compatible with git workflow.

**Comment by rkhamis** [comment]
@zaibon can we close this? Did you verify the solution to set the codeDir when mounted?

**Comment by zaibon** [comment]
nop code has not been updated and nor tested

**Comment by zaibon** [comment]
@ashraffouda didn't you do something about this ?

**Comment by rkhamis** [comment]
Isn't this done?

**Comment by ashraffouda** [comment]
yes this is done
