### ISSUE TITLE
Runs always appear twice

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#240]
![screen shot 2016-11-10 at 11 56 33](https://cloud.githubusercontent.com/assets/13795109/20174148/d1fdbbf8-a73c-11e6-96fb-e759b79d687b.png)

**Comment by rkhamis** [comment]
@yveskerwyn Can you verify that this is still an issue?

**Comment by yveskerwyn** [comment]
We this issue again on Artilium Cockpit:

![screen shot 2016-11-24 at 10 56 36](https://cloud.githubusercontent.com/assets/13795109/20593989/b8ec2c96-b234-11e6-9cb6-ff087e188051.png)

**Comment by john-kheir** [comment]
## Software Version
Verified on 8.1.0 rc1
