### ISSUE TITLE
flush runs

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#241]
See the below situation: step 3 cannot run because step 2 failed

Question: why does step 2 block step 3, there is no dependency between them

Feature request: allow to flush a run, or provide a way to remove the cancel a scheduled action, in this case the action to uninstall a vdcuser service, as defined in a separate blueprint

![screen shot 2016-11-10 at 15 04 03](https://cloud.githubusercontent.com/assets/13795109/20179573/1736d816-a757-11e6-91b9-840040a4558a.png)

**Comment by xmonader** [comment]
node.ovc references a vdc that references a uservdc service. In 8.2.0 you have delete runs from database option.

@zaibon I was told you are working on a way to unschedule action

**Comment by rkhamis** [comment]
Should not be an issue with the new run model: https://github.com/Jumpscale/jumpscale_core8/issues/839
