### ISSUE TITLE
cockpit_chatbot: What the name of the Chatbot

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#242]
What is name of the chatbot for the Cockpit you get when creating a new Cockpit using ays + blueprint, as documented [here](
https://github.com/Jumpscale/jscockpit/blob/master/docs/installation/Using-Blueprint/using-blueprint.md)

Please update the documentation

**Comment by khaledkbadr** [comment]
https://github.com/Jumpscale/jscockpit/blob/master/docs/installation/Using-Telegram/using-Telegram.md

**Comment by zaibon** [comment]
@khaledkbadr This is not the same thing you're talking about.

At the moment, no chat bot is created anymore during installation of the cockpit.
The chat bot still need to be ported to AYS81.

**Comment by yveskerwyn** [comment]
While waiting to have this fixed, is there a way to manually activate a new chatbot for [the existing Cockpit for CentriLogic](https://cl2.aydo2.com/)? I need this for the training tomorrow.

**Comment by zaibon** [comment]
Not really possible at the moment no. cause 
> The chat bot still need to be ported to AYS81.
Which mean the current code doesn't work with AYS81

**Comment by despiegk** [comment]
see other FR about chatbot integration, once that one done this one closes
