### ISSUE TITLE
ERROR: could not find producer:sshkey for service:node!vm4yves, found more than 1

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#246]
Cockpit + repository:  http://85.255.197.84:8288/ays81/Repo?repopath=/optvar/cockpit_repos/yves&repo=yves

When trying executing blueprint using the Cockpit Portal:

<img width="1021" alt="screen shot 2016-11-13 at 17 40 34" src="https://cloud.githubusercontent.com/assets/13795109/20247270/6fdecb86-a9c8-11e6-8713-b6d2e02f9362.png">

**Comment by rkhamis** [comment]
Like I said, this is not an error, merely the result of a previous blueprint
