### ISSUE TITLE
cockpit_portal: Got Internal server error when I used POST for /ays/repository using wrong body

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#248]
Post /ays/repository API with "test" for the body will produce an internal server error.
![screenshot from 2016-11-15 12-15-48](https://cloud.githubusercontent.com/assets/17981089/20301757/4c4735e4-ab2d-11e6-9182-2f6c94558546.png)

**Steps**
1- Open https://cockpit1.aydo2.com/api/apidocs/index.html?raml=api.raml
2- Post /ays/repository API
3- Get the responce

**Comment by rkhamis** [comment]
Seems to me this is the required behavior. If you use the wrong parameters/body you should get an error

**Comment by zaibon** [comment]
This should not return a 500 but a 400 bad request instead.

**Comment by abdulrahmantkhalifa** [comment]
fixed with commit 7b2c64c26cdcf578e17c07081115e92ad9480264
