### ISSUE TITLE
/opt/jumpscale/bin/jspython get deleted after cockpit is deployed.

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jscockpit#253]
After the cockpit is fully deployed and running. if we stop for example the portal and try to restart, system complains that `/opt/jumpscale/bin/jspython` doesn't exists anymore. Which make it impossible to restart the portal.

Current workaround is to copy it back from `/usr/local/bin/jspyhton`.

I didn't manage to find why or when exactly this file is deleted though.

**Comment by despiegk** [comment]
lets verify on 820

**Comment by rkhamis** [comment]
Not relevant anymore
