### ISSUE TITLE
mvp-cockpit: Job Details page doesn't show info

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#259]
![screen shot 2016-11-25 at 14 49 16](https://cloud.githubusercontent.com/assets/13795109/20627141/73afbfc2-b31e-11e6-9b14-09aa6e72f3c6.png)

When clicking the **vdc** hyperlink in the step 2 table:

![screen shot 2016-11-25 at 14 49 25](https://cloud.githubusercontent.com/assets/13795109/20627145/79056a94-b31e-11e6-90b1-fb34e1020e75.png)

**Comment by rkhamis** [comment]
Fixed in https://github.com/Jumpscale/jumpscale_portal8/commit/834dc6f12886dc945296a78fbe323a4757d37f3a and https://github.com/Jumpscale/jumpscale_portal8/commit/33f023dd497f455e148409558c6d90fa36b34305

**Comment by john-kheir** [comment]
Verified on version 8.1.0 rc1
