### ISSUE TITLE
create actions to manage the cockpit

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#26]
## .../cockpit/AYSRepos

- [x] create repo (name)
- [x] link to repo page (see next)

## there need to be AYSRepo page (per repo)

- [x] action: delete
- [x] show explorer (allows creation / manipulation of e.g. blueprints, ...)
-  ays actions:
   - [x] shell (jump to right path & open shellinbox)
   - [x] reload (reloads all ays info into gevent)
   - [x] init
   - [x] commit
   - [x] install
   - [x] simulate
   - [x] execute

## on ays instance page

- [x] action: delete
- [x] explorer

**Comment by zaibon** [comment]
updated the description to reflect progress of the task

**Comment by zaibon** [comment]
Simulator has been created, check a demo at : https://zaibon.barcelona.aydo.com/cockpit/cockpit/AYSRepo/simulate?repo=asasas

**Comment by zaibon** [comment]
Need to have [this issue](https://github.com/Jumpscale/jscockpit/issues/21) solved before I can implement commit.

**Comment by zaibon** [comment]
PR ready :
https://github.com/Jumpscale/jscockpit/pull/39
https://github.com/Jumpscale/jumpscale_portal8/pull/65/files
https://github.com/Jumpscale/jumpscale_core8/pull/315

**Comment by zaibon** [comment]
relates also to https://github.com/Jumpscale/jumpscale_portal8/pull/66
