### ISSUE TITLE
mvp-cockpit: Runs that keep in Running state

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#260]
See Artilium Cockpit:

https://artilium.aydo2.com/ays81/ays81/Runs?repo=/optvar/cockpit_repos/yves03

![screen shot 2016-11-25 at 15 20 59](https://cloud.githubusercontent.com/assets/13795109/20627824/df798266-b322-11e6-8036-6b7380fa2ff2.png)

**Comment by FastGeert** [comment]
@yveskerwyn please add blueprints for these runs? We need more info to reproduce.

**Comment by yveskerwyn** [comment]
@FastGeert just tried it, but could not get to creating new runs because of a new issue in the same repository, filed as [#263](https://github.com/Jumpscale/jscockpit/issues/263)

**Comment by yveskerwyn** [comment]
Fixed
