### ISSUE TITLE
mvp-cockpit: API for updating Actor Templates of a repository

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#261]
Currently in order for instance to update the actor template for a VDC you need to access the Cockpit and execute:

```
cd /optvar/cockpit_repos/repo_name
ays update -n vdc
```

We need API for updating both the shared Actor Templates directory and the Actor Templates directory local to a repository.

Also we need to have that exposed in the Cockpit Portal

**Comment by abdulrahmantkhalifa** [comment]
fixed in https://github.com/Jumpscale/jscockpit/issues/160
