### ISSUE TITLE
Blocking Issue : Can't request any API cos of error in JWT

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#262]
Steps:
1- Login in
https://cockpit2.aydo2.com
2- Generate new JWT
3- Go to /ays/repository API and fill all items in Post method
![screenshot from 2016-11-27 11-20-18](https://cloud.githubusercontent.com/assets/17981089/20647088/843bf7cc-b493-11e6-987a-56d4318d4449.png)

**Actual result**:
![screenshot from 2016-11-27 11-20-59](https://cloud.githubusercontent.com/assets/17981089/20647092/a10fe520-b493-11e6-9fbc-0f4d2ef45f9e.png)

However I used the generated JWT itself.

**Comment by rkhamis** [comment]
also reported here: https://github.com/Jumpscale/jscockpit/issues/254

**Comment by john-kheir** [comment]
Verified on 8.1.0 rc1
