### ISSUE TITLE
Ability to unload all object from memory of the AYS bot.

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#27]
Ability to unload all object from memory of the AYS bot. So everyting is reloaded next time needed.
This is useful in the case you mess with you services and want to make sure everything get reloaded properly

**Comment by zaibon** [comment]
fix in : https://github.com/Jumpscale/jscockpit/commit/e6a918f7654146777eacd0e638f10a10288dc695

**Comment by zaibon** [comment]
I reopen cause I still need to add an action in the portal

**Comment by zaibon** [comment]
action added in cockpit portal: https://github.com/Jumpscale/jumpscale_portal8/commit/a61d1d9518d7ad08a91ebcff7f58931b27348578
