### ISSUE TITLE
install jscockpit through cuisine for development

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#270]
- install on osx (/JS8 root) /ub1604 jscockpit through cuisine
- make sure we can login in debug mode (no itsyou.online required)
- make sure this is documented in this repo
- make sure we can execute a test AYS repo
- put a test AYS repo in this jscockpit repo (with some fake services, this will allow easy testing & demo)

**Comment by abdulrahmantkhalifa** [comment]
- [x] install on osx (/JS8 root) /ub1604 jscockpit through cuisine
- [x] make sure we can login in debug mode (no itsyou.online required)
- [ ] make sure this is documented in this repo
- [ ] make sure we can execute a test AYS repo
- [ ] put a test AYS repo in this jscockpit repo (with some fake services, this will allow easy testing & demo)

**Comment by abdulrahmantkhalifa** [comment]
@rkhamis  dont forget to reasign

**Comment by rkhamis** [comment]
@zaibon seems dependencies of portal are not installed with the all_in_one

**Comment by rkhamis** [comment]
Dependencies and configurations fixed in https://github.com/Jumpscale/jumpscale_core8/commit/d968a08cd3bc154f079f746462d5d11db0017f7b

**Comment by rkhamis** [comment]
docs: https://github.com/Jumpscale/jscockpit/blob/8.1.0/docs/installation/installation.md

**Comment by rkhamis** [comment]
Test repos can be found already in https://github.com/Jumpscale/ays_jumpscale8/tree/8.1.0/examples/
