### ISSUE TITLE
ays tool in jumpscale needs to support blueprints

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#28]
- list
- delete
- archive (means will not be used in init, but not lost)
- execute (just 1 time execute)

put these also as actions in portal

- on ays repo level: list, archive (works for all), execute
- on blueprint level: archive/delete

**Comment by zaibon** [comment]
https://github.com/Jumpscale/jumpscale_core8/commit/08c7aba4d0404ea7bfd7d363179308fc599bff08

**Comment by yveskerwyn** [comment]
@zaibon maybe I'm wrong, but I don't see any documentation for this in the [docs/AYS](https://github.com/Jumpscale/jumpscale_core8/tree/master/docs/AtYourService) documentation folder...

Elsewhere?

**Comment by zaibon** [comment]
AYS command has been updated 
https://gig.gitbooks.io/jumpscale-core8/content/AtYourService/4_AYS_command.html
