### ISSUE TITLE
cockpit-doc: Review the "Installation using an AYS Blueprint" documentation

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#285]
## GOAL:

Provide more (verbose) details based on experience

## DESCRIPTION:

https://gig.gitbooks.io/cockpit/content/installation/Using-Blueprint/using-blueprint.html

Add:

```
pip install pytoml
pip install pytoml

```

Steps:

1 - cd /opt/code/github/jumpscale/jumpscale_core8/; git checkout cockpit-0.9

2- cd /opt/code/github/jumpscale/ays_jumpscale8/; git pull

3- mkdir -p /opt/code/github/jumpscale/cockpit_deploy/blueprints

4- touch /opt/code/github/jumpscale/cockpit_deploy/.ays

5- do git init in /opt/code/github/jumpscale/cockpit_deploy/

6- add your repo information in the /opt/code/github/jumpscale/cockpit_deploy/.git/config

7 - add blueprint to blueprints directory

8 - ays blueprint

9 - ays run

**Comment by despiegk** [comment]
should not do too much, will change for 9.x and is coming soon

**Comment by rkhamis** [comment]
Just update link to example please when done with https://github.com/Jumpscale/jscockpit/issues/367

Change to ays repo create
