### ISSUE TITLE
cannot execute run

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#286]
![image](https://cloud.githubusercontent.com/assets/6021844/20671484/ee53fbd8-b596-11e6-95be-8305a09320de.png)

![image](https://cloud.githubusercontent.com/assets/6021844/20671488/f54e9114-b596-11e6-9d11-c0ffec12c731.png)

the repo does exist, lets try to do on ubuntu node
my machine is osx

**Comment by FastGeert** [comment]
@rkhamis don't forget to reassign as agreed with Abdelrahmen

**Comment by FastGeert** [comment]
@despiegk are you still blocked on this?
