### ISSUE TITLE
need form on repo page to allow direct blueprint posting & execution

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#287]
![image](https://cloud.githubusercontent.com/assets/6021844/20712020/d08e8da0-b65b-11e6-8b30-037083feb9f4.png)

- there should be form on this page
- in this form people can put blueprint statements
   - can be actions
   - recurring ...
- blueprint gets executed (not run) = do the init
- remark: there is no blueprint leftover on filesystem

**Comment by despiegk** [comment]
also put link to documentation about how blueprint is constructed
also link to example blueprints

**Comment by FastGeert** [comment]
@despiegk I agree this wil make it much easier to handle, but do we needed in the mvp for cockpit today?

**Comment by despiegk** [comment]
y

**Comment by rkhamis** [comment]
> there should be form on this page

Would it make more sense to put it on the blueprints page?

> in this form people can put blueprint statements
can be actions
recurring ...

Only for special (actions/recurring/....)  blueprints? Or for all kinds of blueprints. Deployment ones as well?

> blueprint gets executed (not run) = do the init
remark: there is no blueprint leftover on filesystem

If we only do init and no run, then delete the blueprint file, we gain nothing in terms of actions.
How about we do those blueprints that they get archived by default after run?
that way we get a nice overview of all blueprints that have been part of this repo?

**Comment by rkhamis** [comment]
@samaradel can we make it prettier? See https://github.com/Jumpscale/jumpscale_portal8/commit/c0869ca2565820834ac460baf22645e7b6774fd0

**Comment by rkhamis** [comment]
Fixed!

**Comment by john-kheir** [comment]
Verified on 8.1.0 rc1
