### ISSUE TITLE
run did not work

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#292]
![image](https://cloud.githubusercontent.com/assets/6021844/20866922/5a5a85bc-ba52-11e6-9c32-47d3957664cd.png)

**Comment by rkhamis** [comment]
Fixed in https://github.com/Jumpscale/jumpscale_portal8/commit/834dc6f12886dc945296a78fbe323a4757d37f3a

**Comment by john-kheir** [comment]
## Version
8.1.0 rc1
