### ISSUE TITLE
profile not working in job

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#293]
![image](https://cloud.githubusercontent.com/assets/6021844/20866930/81bbf5aa-ba52-11e6-89d2-cf3b247b6ad6.png)

**Comment by zaibon** [comment]
I can't reproduce the error shown in the screenshot.

But I inspected the code of the `aysprofile` macro and I think there are some issue indeed.
- sometime the server get macro stays stuck on : https://github.com/Jumpscale/jumpscale_portal8/blob/master/apps/portalbase/AYS81/.macros/page/aysjobprofile/3_aysjobprofile.py#L13 no idea why yet.
- the macro always set the iframe to point to localhost, wich in real work won't work.
I propse the following to resolve this.
```diff
diff --git a/apps/portalbase/AYS81/.macros/page/aysjobprofile/3_aysjobprofile.py b/apps/portalbase/AYS81/.macros/page/aysjobprofile/3_aysjobprofile.py
index de33b6d..11edfd2 100755
--- a/apps/portalbase/AYS81/.macros/page/aysjobprofile/3_aysjobprofile.py
+++ b/apps/portalbase/AYS81/.macros/page/aysjobprofile/3_aysjobprofile.py
@@ -1,3 +1,4 @@
+from urllib import parse
 
 def main(j, args, params, tags, tasklet):
     page = args.page
@@ -20,7 +21,11 @@ def main(j, args, params, tags, tasklet):
     job = job.objectGet()
     j.sal.fs.writeFile(filename=stats, contents=job.model.dbobj.profileData, append=False)
 
-    p = Popen(['timeout', '1m', 'python3', '-u', '/usr/local/bin/snakeviz', '-s', stats], stdout=PIPE)
+    host = args.requestContext.env.get('SERVER_NAME','localhost')
+    if host.find(":") != -1:
+        host = host.split(":")[0]
+
+    p = Popen(['timeout', '1m', 'python3', '-u', '/usr/local/bin/snakeviz','-H', '0.0.0.0', '-s', stats], stdout=PIPE)
 
     line = p.stdout.readline().decode()
     while 'http' not in line:
@@ -28,7 +33,9 @@ def main(j, args, params, tags, tasklet):
         line = line.decode()
         #print(line)
 
-    page.addHTML("<iframe src=%s frameborder='0' width=100%% height=600 position=absolute></iframe>" % line)
+    u = parse.urlparse(line)
+    u2 = u._replace(netloc="%s:%s" % (host, u.port))
+    page.addHTML("<iframe src=%s frameborder='0' width=100%% height=600 position=absolute></iframe>" % u2.geturl())
 
     params.result = page
```

But then there is another problem. In production the portal is proxies by caddy and only port 80 and 443 are open, which mean the client browser won't be able to access the snakeviz server. @rkhamis  any idea ?

**Comment by rkhamis** [comment]
@zaibon error on page is already fixed.
I just didn't figure out why it sometimes hangs on `ps aux`

The proxy could be an issue indeed.

**Comment by john-kheir** [comment]
Verified on version 8.1.0 rc1
