### ISSUE TITLE
explorer hangs in AYS

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#295]
![image](https://cloud.githubusercontent.com/assets/6021844/20867011/641426ce-ba54-11e6-85bd-a6c2c790b6f3.png)

but not always

- its only when go and click around somewhat in AYS & then try
- if I restart portal and use the link  
   - http://localhost:8200/ays81/ays81/Explorer?repo=/JS8/optvar/cockpit_repos/test
   - it works

**Comment by rkhamis** [comment]
Can't reproduce on Ubuntu.

**Comment by abdulrahmantkhalifa** [comment]
reproduced on ubuntu
