### ISSUE TITLE
mvp-cockpit: cannot create new repository

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#297]
http://172.98.207.199:7182/ays81/Repos

![screen shot 2016-12-05 at 10 32 14](https://cloud.githubusercontent.com/assets/13795109/20879929/45972e26-bad6-11e6-925f-0f09806a430a.png)

![screen shot 2016-12-05 at 10 32 24](https://cloud.githubusercontent.com/assets/13795109/20879934/498a5576-bad6-11e6-9441-c20e79380181.png)

**Comment by rkhamis** [comment]
cannot reproduce
