### ISSUE TITLE
form behavior for blueprints change request

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#305]
![image](https://cloud.githubusercontent.com/assets/6021844/20887342/9c48be6e-bb13-11e6-8864-e10464bdf41f.png)

- call apply
- in actions
    - have install (which dus install action & run)
    - keep run
    - add cleanup (which removes logs & run info)

**Comment by rkhamis** [comment]
Duplicate of https://github.com/Jumpscale/jscockpit/issues/301
