### ISSUE TITLE
Error message after deploy a virtual machine

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#306]
I used the following blueprint to create a virtual machine but I got an error
**blueprint**
```g8client__islam:
    url: 'be-g8-4.demo.greenitglobe.com'
    login: 'ramez'
    password: '123456789'

vdc__f0d7583879:
    description: '9008985629'
    g8client: 'islam'
    account: '553137d912'
    location: 'be-g8-4'
    uservdc:
        - 'ramez'

node.ovc__238c1acd8a:
    os.image: 'Ubuntu 16.04 x64'
    bootdisk.size: 10
    sizeID: 2
    vdc: f0d7583879

actions:
   - action: 'install'
```

**Error**
```
[{u'jobs': [{u'actor_name': u'sshkey', u'logs': [], u'service_name': u'auto_0', u'action_name': u'install', u'state': u'ok', u'key': u'bc900e03189830fb729de36bda0ab95c', u'service_key': u'0ade23510a99059dfbf5073b2d04eb4b'}, {u'actor_name': u'vdcfarm', u'logs': [], u'service_name': u'auto_92', u'action_name': u'install', u'state': u'ok', u'key': u'4d4733335fdeed94cfbe93f80046f4a7', u'service_key': u'7e1ea39d7b28ae272f5815be56b65a3b'}, {u'actor_name': u'g8client', u'logs': [], u'service_name': u'islam', u'action_name': u'install', u'state': u'ok', u'key': u'c2eaeb2167811eeb4691263a6315fafb', u'service_key': u'534946d08bbfb4518af9d535f80c3d72'}], u'number': 1}, {u'jobs': [{u'actor_name': u'vdc', u'logs': [], u'service_name': u'9fe00efb35', u'action_name': u'install', u'state': u'ok', u'key': u'd97ea9a6e55eef0ed536d75181e0e160', u'service_key': u'68b089da4a9bf84d281c8a06f0e12b44'}], u'number': 2}, {u'jobs': [{u'actor_name': u'node.ovc', u'logs': [{u'category': u'out', u'epoch': 0, u'tags': None, u'log': None, u'level': 0}, {u'category': u'trace', u'epoch': 1481114674, u'tags': u'', u'log': u'Traceback (most recent call last):
  File &quot;/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py&quot;, line 195, in start
    res = self.method(**self.args)
  File &quot;/tmp/actions/node.ovc/install.py&quot;, line 61, in action
    executor.cuisine.ssh.authorize(&quot;root&quot;, sshkey.model.data.keyPub)
  File &quot;/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineSSH.py&quot;, line 137, in authorize
    d = self._cuisine.user.check(user, need_passwd=False)
  File &quot;/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineUser.py&quot;, line 85, in check
    _, d, _ = self._cuisine.core.run(&quot;getent passwd | egrep \'^%s:\' ; true&quot; % (name))
  File &quot;/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py&quot;, line 1033, in run
    if &quot;cygwin&quot; in self.uname:
  File &quot;/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py&quot;, line 1251, in uname
    self._uname = self._executor.execute(&quot;uname -a&quot;, showout=False)[1].lower()
  File &quot;/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py&quot;, line 173, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File &quot;/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py&quot;, line 251, in execute
    ch = self.transport.open_session()
  File &quot;/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py&quot;, line 179, in transport
    &quot;Could not connect to %s:%s&quot; % (self.addr, self.port))
JSExceptions.RuntimeError: ERROR: Could not connect to 10.101.110.77:22 ((type:runtime.error)
', u'level': 1}], u'service_name': u'7afdbb53f6', u'action_name': u'install', u'state': u'error', u'key': u'fdcbae7556a047e86d408ce4480e76d4', u'service_key': u'0e6c604eee8c4774c6f91bc0ae7831fb'}], u'number': 3}, {u'jobs': [{u'actor_name': u'os.ssh.ubuntu', u'logs': [], u'service_name': u'7afdbb53f6', u'action_name': u'install', u'state': u'new', u'key': u'9293cdc734ac9fdc94f87b0940f32f0f', u'service_key': u'6ff1aa7159bb3f5f2279544a08d9ce6f'}, {u'actor_name': u'test_snapshot', u'logs': [], u'service_name': u'a3910ac0e2', u'action_name': u'install', u'state': u'new', u'key': u'172a8e59cb2791274b27b02efb80f09a', u'service_key': u'02c832f105d8e0327d5183a35573bccf'}], u'number': 4}]
```

I checked the eviroment and I found that the virtual machine has been created.

**Comment by grimpy** [comment]
Probably a problem with the network

**Comment by grimpy** [comment]
Issue with network indeed a cockpit deployed on a public ip can not reach our private network.

**Comment by islamTaha12** [comment]
@grimpy same error 
`<testsuite errors="1" failures="0" name="Cockpit_Testing" skip="0" succeeded="0" tests="1"><testcase blueprint_template="cockpit_testing/Framework/TestCasesTemplate" name="create_cloudspace_test" result="ERROR : f22266a3ff [{u'jobs': [{u'actor_name': u'vdcfarm', u'logs': [], u'service_name': u'auto_94', u'action_name': u'install', u'state': u'ok', u'key': u'725c1873020d04f4dc0c1d7038d71af1', u'service_key': u'31b3c5896bb233820a03dfbd047f7a5b'}, {u'actor_name': u'sshkey', u'logs': [], u'service_name': u'auto_0', u'action_name': u'install', u'state': u'ok', u'key': u'aa6c1fed7d069c0a169a923a22890caf', u'service_key': u'6cc18089190079ba0e8f95f1bbbb4289'}, {u'actor_name': u'g8client', u'logs': [], u'service_name': u'islam', u'action_name': u'install', u'state': u'ok', u'key': u'00c889ece4df7b60b09157be5299ccbb', u'service_key': u'9194eeaaf768bea46c24c2c52da94955'}], u'number': 1}, {u'jobs': [{u'actor_name': u'vdc', u'logs': [], u'service_name': u'fd6d0afe9e', u'action_name': u'install', u'state': u'ok', u'key': u'31d6cd4ba77960c03009b94ad878b7e5', u'service_key': u'a352ca5c0592b62247564f241bd72ed5'}], u'number': 2}, {u'jobs': [{u'actor_name': u'node.ovc', u'logs': [{u'category': u'out', u'epoch': 0, u'tags': None, u'log': None, u'level': 0}, {u'category': u'trace', u'epoch': 1481198436, u'tags': u'', u'log': u'Traceback (most recent call last):
  File &quot;/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py&quot;, line 195, in start
    res = self.method(**self.args)
  File &quot;/tmp/actions/node.ovc/install.py&quot;, line 61, in action
    executor.cuisine.ssh.authorize(&quot;root&quot;, sshkey.model.data.keyPub)
  File &quot;/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineSSH.py&quot;, line 137, in authorize
    d = self._cuisine.user.check(user, need_passwd=False)
  File &quot;/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineUser.py&quot;, line 85, in check
    _, d, _ = self._cuisine.core.run(&quot;getent passwd | egrep \'^%s:\' ; true&quot; % (name))
  File &quot;/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py&quot;, line 1033, in run
    if &quot;cygwin&quot; in self.uname:
  File &quot;/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py&quot;, line 1251, in uname
    self._uname = self._executor.execute(&quot;uname -a&quot;, showout=False)[1].lower()
  File &quot;/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py&quot;, line 173, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File &quot;/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py&quot;, line 251, in execute
    ch = self.transport.open_session()
  File &quot;/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py&quot;, line 179, in transport
    &quot;Could not connect to %s:%s&quot; % (self.addr, self.port))
JSExceptions.RuntimeError: ERROR: Could not connect to 192.168.28.50:22 ((type:runtime.error)
', u'level': 1}], u'service_name': u'599cc9554c', u'action_name': u'install', u'state': u'error', u'key': u'df42122e6e1ddcf77624ce460fb238eb', u'service_key': u'733c61e0b2cea43d8a71bc0fb3fcef4b'}], u'number': 3}, {u'jobs': [{u'actor_name': u'os.ssh.ubuntu', u'logs': [], u'service_name': u'599cc9554c', u'action_name': u'install', u'state': u'new', u'key': u'5f13533706c62c6492fc73af9abe9776', u'service_key': u'd4bce28e09a7683bb32ad956fd1d4e8a'}], u'number': 4}]" time="60.34" /></testsuite>
`

**Comment by FastGeert** [comment]
@ramezsaeed I see in your log output above that you try to create an ssh connection to from a public ip towards a private ip, so I think this is a setup problem.

**Comment by rkhamis** [comment]
Fixed in https://github.com/Jumpscale/ays_jumpscale8/pull/118

**Comment by john-kheir** [comment]
Verified on version 8.1.0 rc1
