### ISSUE TITLE
mvp-cockpit: not all repositories show up in the Cockpit Portal

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#311]
Cockpit: 
```
ssh cloudscalers@172.98.207.199 -p7122 -A
```

Password is **iZASUo7tE**

Actual cockpit repositories, **four**:
```
root@vm-93:/optvar/cockpit_repos# ls
tony01	yves01	yves02	yves03
```

When using the Cockpit API, **only two of four** are returned:
```
curl -X GET http://172.98.207.199:5000/ays/repository
[{"git_url": "git@github.com:yveskerwyn/tony01.git", "name": "tony01", "path": "/optvar/cockpit_repos/tony01"}, {"git_url": "git@github.com:yveskerwyn/cockpit_repo_yves3.git", "name": "yves03", "path": "/optvar/cockpit_repos/yves03"}]
```

When checking the [Cockpit Portal](http://172.98.207.199:82/ays81/Repos) **only three of four** are displayed:

![screen shot 2016-12-09 at 17 57 41](https://cloud.githubusercontent.com/assets/13795109/21057219/011e3eea-be39-11e6-9629-0a2ce0008768.png)

**Comment by john-kheir** [comment]
## Software Version
Verified on 8.1.0 rc1
