### ISSUE TITLE
Link in error

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jscockpit#315]
![error page](https://cloud.githubusercontent.com/assets/15011431/21138631/9ab655fa-c137-11e6-8a00-3d4a5fc78bc1.png)

**Comment by rkhamis** [comment]
@john-kheir can you write the steps where this happened?

**Comment by john-kheir** [comment]
ip:port/ays81/AYS81/Runs .. just directly type this url n your browser .. It is just link in error

**Comment by rkhamis** [comment]
That's just evil and wrong. Created a bug to harden all wiki pages against such sabotage -.-
See: https://github.com/Jumpscale/jumpscale_portal8/issues/118
