### ISSUE TITLE
Page doesn't refresh automatically after removing all runs

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jscockpit#319]
![screenshot from 2016-12-22 12-58-45](https://cloud.githubusercontent.com/assets/15011431/21423687/01be3518-c847-11e6-8a56-12d443edb506.png)
![removeruns](https://cloud.githubusercontent.com/assets/15011431/21423688/076706a2-c847-11e6-9424-2f3a6b700526.png)

**Comment by xmonader** [comment]
https://github.com/Jumpscale/portal9/commit/e875f86121f2799c6baca67c561b5d294b86c503
