### ISSUE TITLE
User should be able to update snapshotting interval & retention periods

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#322]
According to the implemented autosnapshotting service, user can't modify interval or retention periods.

**Cockpit branch**
8.1.0

**Comment by rkhamis** [comment]
https://github.com/Jumpscale/ays_jumpscale8/tree/479e59a43d35d6e72ab3a6db535f87754cf13aaa/templates/ovc/autosnapshotting
