### ISSUE TITLE
Internal server error when execute wrong blueprint

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#323]
**Description**
Execute any blueprint with wrong paramter will produce an internal server error.

**Example**
Execute the following blueprint which has 'locations' instead of "location"
![screenshot from 2016-12-27 16-54-01](https://cloud.githubusercontent.com/assets/17981089/21502018/75e29bd4-cc55-11e6-82dc-c7fd8c478b40.png)

**Actual Result**
![screenshot from 2016-12-27 16-54-47](https://cloud.githubusercontent.com/assets/17981089/21502024/7d62019c-cc55-11e6-806c-daa5dac2010a.png)

**Expected result**
System should verify the blueprint and handle wrong parameters.

**Cockpit version**

JumpScale

    Core: 8.1.0rc2-4-g776daea
    Portal: 8.1.0rc2-1-gb748c00

JSCockpit

    JSCockpit: 8.1.0rc2

**Repo**
8.1.0

**Comment by john-kheir** [comment]
## Tested on 8.1.1
![bg](https://cloud.githubusercontent.com/assets/15011431/23506717/57d83e8e-ff52-11e6-901f-64adc10c8df1.png)
This blueprint shouldn't be accepted in the first place

**Comment by abdulrahmantkhalifa** [comment]
u want to implement client side checks that is really not a good idea

**Comment by abdulrahmantkhalifa** [comment]
trying to reproduce blocked on https://github.com/Jumpscale/jscockpit/issues/364 @ashraffouda

**Comment by ashraffouda** [comment]
not working on that issue right now

**Comment by xmonader** [comment]
You should get errors like this. 

![bperrors](https://cloud.githubusercontent.com/assets/64129/23888352/385f12d4-0890-11e7-9dec-e97040035190.png)



Acceptance of a blueprint is a totally different thing in 8.1.1 (as validation is done during service creation -for malicious manipulation of arguments- not during blueprint execution).

**Comment by john-kheir** [comment]
## Verified on 8.1.1
