### ISSUE TITLE
Daemon is going in infinite loop when it try to execute not handled commands

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#324]
**Steps**
- Execute the following blueprint and check the daemon logs

> g8client__main:
>     url: 'du-conv-2.demo.greenitglobe.com'
>     login: 'driver'
>     password: 'KrOe6gE9K5nCQdmretfXnj'
>     account: '6c3cc88d36'
> 
> vdc__d3ce57eae2:
>     g8client: 'main'
>     location: 'du-conv-2.demo.greenitglobe.com'
> 
> disk.ovc__disk1:
>   size: 1000
> 
> s3__s3vm:
>     vdc: 'd3ce57eae2'
>     disk:
>       - 'disk1'
>     domain: 'mystorage.com'

**Actual result**
![screenshot from 2016-12-28 13-55-15](https://cloud.githubusercontent.com/assets/17981089/21521483/ff8218e6-cd05-11e6-9f0c-99fce03ebff6.png)

Daemon goes into infinite loop to do autoscale job and it doesn't stop at any point unless the user destroy the repo.

**Expected result**
Daemon shouldn't be stuck at any point. It should handle this kind of error.

**Cockpit repo**
8.1.0

**Comment by rkhamis** [comment]
Fixed in 820
