### ISSUE TITLE
Destroy a repo from the portal is confusing

### ISSUE THREAD

**Issue by ramezsaeed** [Jumpscale/jscockpit#327]
- when I destroy a repo from the cockpit portal, its deleted from the portal repo table
- but it still exists in the repo directory on the cockpit machine
- after while I can see the same repo again in the portal repo table !!!!

## Expected solutions:
1- destroy the repo from portal should also delete the related directory from the cockpit machine.
2- or after destroy only mark the repo as destroyed and don't remove it from the portal table or the cockpit machine.

**Comment by rkhamis** [comment]
We can delete repos instead of destroying them to keep the portal view and the fs consistent.

**Comment by alichaddad** [comment]
On 8.2.0 deleting repos from the portal deletes them from the fs. The action is renamed to delete in the repos page.
