### ISSUE TITLE
No blueprints found when applying blueprint without a name

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jscockpit#328]
# Scenario
1- Create a repo and apply any blue print without providing a name
![bug1](https://cloud.githubusercontent.com/assets/15011431/21588986/542affb4-d0f5-11e6-8b30-185a50e98de6.png)
2- No blueprint founds in the repo's blueprints
![bug2](https://cloud.githubusercontent.com/assets/15011431/21588988/55f25fae-d0f5-11e6-9191-023db56c8ad0.png)

## Software Verison

JumpScale

    Core: 8.1.0rc2-4-g776daea
    Portal: 8.1.0rc2-1-gb748c00

JSCockpit

    JSCockpit: 8.1.0rc2

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/jumpscale_portal8/commit/e4c15039e21bb11976ae3b4fa8a603f74d49a979

**Comment by john-kheir** [comment]
Verified on 8.1.1
