### ISSUE TITLE
Redis Maximuim memory hangs the server

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#331]
**Description**
I have a cockpit machine which was installed week ago. I faced internal server error when I tried accessing the portal. I found the following redis maximum memory issue.

![screenshot from 2017-01-04 11-38-59](https://cloud.githubusercontent.com/assets/17981089/21638220/220ac300-d273-11e6-9809-edad081d2ca9.png)

**Version**
8.1.0

**Comment by rkhamis** [comment]
Can you check the current maximum memory limit?

**Comment by islamTaha12** [comment]
Its 95mb
