### ISSUE TITLE
Cockpit portal is crashing after installation

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#332]
**Description**
I installed a new cockpit from 8.1.0 branch and the portal isn't running. Please check the following error.
![screenshot from 2017-01-05 13-28-22](https://cloud.githubusercontent.com/assets/17981089/21679186/5a46d4f6-d34b-11e6-9514-a4e02a029ae5.png)

**version**
8.1.0

**Comment by rkhamis** [comment]
This is because I merged into the wrong version branch. My bad. Already reverted and moved to version 8.1.1

**Comment by islamTaha12** [comment]
Verified on 8.1.0
