### ISSUE TITLE
Hierarchical visualisation of services based on dependencies tree

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#346]
The current **AYS Services** page shows all services for a specific repository.

In addition to showing this in a **flat table** we need a **hierarchical representation**based on the dependencies  tree

![screen shot 2017-01-16 at 14 58 15](https://cloud.githubusercontent.com/assets/13795109/21985698/40310e24-dbfc-11e6-8a6d-b755274547d8.png)

**Comment by rkhamis** [comment]
@samaradel can you maybe give us ideas on how to do this?

**Comment by xmonader** [comment]
Implemented in https://github.com/Jumpscale/portal9/commit/117769207523bb2ac678ae95b78e460e80f0590e
