### ISSUE TITLE
Install action - obsolete?

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#347]
![screen shot 2017-01-16 at 15 20 46](https://cloud.githubusercontent.com/assets/13795109/21986376/764987ae-dbff-11e6-91c0-0a20f5e18f8b.png)

**Comment by rkhamis** [comment]
It's more of a shortcut than anything. Since the `install` action is the most common and widely used action. It's bad practice, though.

I'm perfectly fine with removing it. We should decide this in a stakeholder's meeting, I guess.

**Comment by yveskerwyn** [comment]
It OK for me to keep it there
