### ISSUE TITLE
Incorrect Actor Template information on Service Detail page

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#348]
It shows the actor template of the parent...

Some examples:

- **vdc** instead of **node.ovc** on http://85.255.197.77:82/ays81/ays81/ays81/Service?aysrole=node&aysname=s3server&ayspath=/optvar/cockpit_repos/yves01
- **node** instead of **os.ssh.ubuntu** on http://85.255.197.77:82/ays81/ays81/ays81/Service?aysrole=os&aysname=caddy&ayspath=/optvar/cockpit_repos/yves01
- **os** instead of **scality** on http://85.255.197.77:82/ays81/ays81/ays81/Service?aysrole=scality&aysname=app&ayspath=/optvar/cockpit_repos/yves01
- **vdcfarm** instead of **vdc** on http://85.255.197.77:82/ays81/ays81/ays81/Service?aysrole=vdc&aysname=vdc4s3&ayspath=/optvar/cockpit_repos/yves01
...

Check yourself for all services: http://85.255.197.77:82/ays81/ays81/Services?ayspath=/optvar/cockpit_repos/yves01

**Comment by rkhamis** [comment]
Cherry-picked to 8.1.1 too

**Comment by john-kheir** [comment]
Verified on 8.1.1
