### ISSUE TITLE
Missing Role info in Parent section of Service Details page 

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#349]
See: http://85.255.197.77:82/ays81/ays81/ays81/Service?aysrole=vdc&aysname=vdc4s3&ayspath=/optvar/cockpit_repos/yves01

Screenshot below.

Also, fix following very confusing inconsistencies:
- Change **Role** column header to **Actor**
- Change **Instance** column header to **Service**
- Same for the **Producers** section/table
- Change **Name** column header to **Service**
- In both case put the **Service** (Instance/Name) column first, and **Actor** (role) column second
- Make both tables and its columns equally wide

![screen shot 2017-01-16 at 17 46 39](https://cloud.githubusercontent.com/assets/13795109/21991690/dca05262-dc13-11e6-9675-58f720808f48.png)

**Comment by xmonader** [comment]
![selection_040](https://user-images.githubusercontent.com/64129/27021796-fa325fb4-4f4a-11e7-8a0d-00fbd5e1014b.png)

Not an issue.

**Comment by yveskerwyn** [comment]
OK let's keep **Role** as header

**Comment by xmonader** [comment]
https://github.com/Jumpscale/portal9/pull/19
