### ISSUE TITLE
Drop the word **AYS** from the Services page

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#351]
This also makes it more consistent with the breadcrumb.

![screen shot 2017-01-16 at 18 19 26](https://cloud.githubusercontent.com/assets/13795109/21992969/e47303b8-dc18-11e6-9853-5d3276614f32.png)

**Comment by xmonader** [comment]
https://github.com/Jumpscale/portal9/commit/a5afd26d797d98ab7001aee95c09a18d6c4e2050
