### ISSUE TITLE
Bypass blueprint cheking using the API send blueprint.

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#352]
**Description**
The API send blueprint doesn't make a blueprint check like the portal.

**Hint**
This blueprint has an old VM actors.

**Actual Result**
![screenshot from 2017-01-18 12-18-53](https://cloud.githubusercontent.com/assets/17981089/22060224/a19d6b62-dd78-11e6-9606-70b05d8b88ae.png)

**Blueprint**
![screenshot from 2017-01-18 12-21-18](https://cloud.githubusercontent.com/assets/17981089/22060270/ca466514-dd78-11e6-8c85-3c4fa3e1434b.png)

**Expected result**
Post API blueprint should check it too.

**API logs**

> capnperror: struct has no such member; name = diskSize
>  ((type:input.error)
> 127.0.0.1 - - [18/Jan/2017 11:17:57] "POST /ays/repository/ec3edfc87e/blueprint/virtsad?instance=&role= HTTP/1.1" 500 -

**Cockpit Version**
JumpScale
    Core: v8.1.0-22-ge370ba1
    Portal: v8.1.0
JSCockpit
    JSCockpit: 8.1.0rc2-25-ge40f822

**Installing version**
8.1.1

**Comment by rkhamis** [comment]
Done in 8.2.0
