### ISSUE TITLE
Explorer doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#353]
http://85.255.197.77:82/ays81/ays81/Explorer?repo=/optvar/cockpit_repos/yves12

**Open folder** keeps "spinning":

![screen shot 2017-01-19 at 15 08 54](https://cloud.githubusercontent.com/assets/13795109/22109719/3a19ddcc-de59-11e6-822f-38aaf4dcda58.png)

**Comment by john-kheir** [comment]
Verified on 8.1.1
