### ISSUE TITLE
Show progress of a run

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#354]
Currently when starting a run it stays visualized in the "new" state until it finishes:

![screen shot 2017-01-20 at 15 24 46](https://cloud.githubusercontent.com/assets/13795109/22152743/98c9ec1a-df24-11e6-8f11-26bbe0de8f3f.png)

Also on the service page you see all actors being in a "new" state, even while some of them are already OK:

![screen shot 2017-01-20 at 15 26 44](https://cloud.githubusercontent.com/assets/13795109/22152861/074acaba-df25-11e6-8fe4-c5d1013df0c0.png)

We need a way to see the progress:
- show which step already finished successfully
- what the engine is doing now

**Comment by xmonader** [comment]
Implemented in https://github.com/Jumpscale/portal9/commit/5334cde27584cf6da3ff8be38edd59c6db964d8b (Now we can see the state of a run and its steps or all of the runs without refreshing the page)
