### ISSUE TITLE
Rename "services" to "actors"

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#355]
In the Cockpit it are **actors** (not services) creating and managing the lifecycle of the **services**, which are running on a G8 or even elsewhere

To reflect this please change:
- **Repository Details** page:
  - link: **Services** -> **Actors**

-  **Services** page -> **Actors** page
   - heading: **Services Page** to  the **Actors**
   - first column header: **Actore Name** - > **Actor Template Name**
   - second column header: **Name** -> **Actor Name**
   - Swap the first two colums

- **Service Details** page -> **Actor Details** page
  - header: **Service values** -> **Actor Values** (with a big V)
  - header: **Service Actions** -> **Actor Actions**

- Breadcrumb:
  - AYS81 Portal / AYS81 / Repo {name} / Services -> **Cockpit Portal** / **Repository**: {name} / **Actors**
  - AYS81 Portal / AYS81 / Repo {name} / Services / Service {name} -> **Cockpit Portal** / **Repository**: {name} / **Actors** / **Actor:** {name}

**Comment by rkhamis** [comment]
We now have actortemplates, actors and services
