### ISSUE TITLE
remove "state" column for Services overview page

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#356]
See the successful Run, state is **ok**:

![screen shot 2017-01-20 at 15 44 01](https://cloud.githubusercontent.com/assets/13795109/22153357/4aaa65d4-df27-11e6-91f3-ff4315be41e9.png)

But on the Services page all actors still show as to be in the **new** state:

 
![screen shot 2017-01-20 at 15 45 00](https://cloud.githubusercontent.com/assets/13795109/22153393/6cf74184-df27-11e6-9c6b-a0474ec1255a.png)

**Comment by rkhamis** [comment]
To be honest, I'm not sure what an AYS service state should signify. There's a state for every action. I feel this whole column is entirely misleading and should be removed.

**Comment by xmonader** [comment]
https://github.com/Jumpscale/portal9/commit/25d79664e5a902cf29a96ed7c1ed408e613dd648
