### ISSUE TITLE
ays daemon doesn't schedule recurring task

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jscockpit#363]
on a development cockpit, process seems started, but nothing gets scheduled. Starting a new daemon fixes it.

**Comment by rkhamis** [comment]
First of all we must prevent jobs from hanging in the daemon, using up our pool of available slots.
Prevention measures:

 1. Jobs in error get popped out of job array
 2. Jobs time out eventually. Suggest an hour and a half.
 3. Let's add better logging so we can figure out if something else is going wrong.


This should also fix #365

**Comment by ahussein** [comment]
imho, it should be possible to configure timeout for each job and if no specific timeout is set in the job configuration then a global timeout should be used.

**Comment by rkhamis** [comment]
I guess we can add configuration to the actor that allows setting timeout.
Maybe something like

```
timeout.<function name> = 1h,
```

**Comment by rkhamis** [comment]
I'll create that as feature request on 8.2.0, I don't want to overload this milestone.

**Comment by zaibon** [comment]
I also think it's a good idea to allow people to set timeout on their jobs.
Now we have no way to know what time we should allow for each job.
