### ISSUE TITLE
False Alarm from cockpit portal

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jscockpit#364]
# Scenario 
1- Make a new repo and put a blueprint and press apply 
![p1](https://cloud.githubusercontent.com/assets/15011431/22637535/02b020e4-ec4b-11e6-8a79-2fb047455497.png)
![p2](https://cloud.githubusercontent.com/assets/15011431/22637537/0459ec2c-ec4b-11e6-857a-05c4978870c0.png)
## Issues
- we got a bad request for a well written blueprint
- As shown in the 2nd figure, Despite the the bad request the blueprint has been executed on the cockpit machine

# Version
jscockpit: 8.1.1
js core: 8.1.1
ays: 8.1.1

**Comment by ashraffouda** [comment]
can not reproduce, on a fresh cockpit

**Comment by yveskerwyn** [comment]
I'm suffering from the same problem:

![screen shot 2017-02-16 at 16 07 32](https://cloud.githubusercontent.com/assets/13795109/23026642/2fae2e8c-f462-11e6-9037-d2ee5eb13952.png)

See repositories:
- http://10.101.101.135:82/ays81/repo?repo=yves03&repopath=/optvar/cockpit_repos/yves03
- http://10.101.101.135:82/ays81/repo?repo=yves04&repopath=/optvar/cockpit_repos/yves04

At CLI:

![screen shot 2017-02-16 at 16 07 39](https://cloud.githubusercontent.com/assets/13795109/23026691/5cb189ec-f462-11e6-9c69-1fd0f8f938d6.png)

**Comment by yveskerwyn** [comment]
@rkhamis has been investigating this, it turned out that AYS failed to create a directory, first she thought that it has to do with ssh key generation, until we ran into volume driver problems:

```
OSError: [Errno 30] Read-only file system: '/optvar/cockpit_repos/yves05/services/vdcfarm!auto_11/vdc!myvdc/node!myowncloud/os!myowncloud/app_docker!appdocker/service.json'
```

So maybe the problem is all together related to storage issues?

**Comment by rkhamis** [comment]
Definitely. I'll keep this open for one final test. But that's definitely the storage issue.

**Comment by john-kheir** [comment]
This problem keeps happing with me a lot

**Comment by john-kheir** [comment]
## Verified on 8.1.1
