### ISSUE TITLE
Wrong version is provided in the portal

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jscockpit#366]
![cockpit333](https://cloud.githubusercontent.com/assets/15011431/22862803/51af5ec4-f13e-11e6-84fc-332af1d9a4d7.png)
![cockpit11](https://cloud.githubusercontent.com/assets/15011431/22862804/534e83cc-f13e-11e6-9778-01a722811884.png)

**Comment by rkhamis** [comment]
[git describe](https://git-scm.com/docs/git-describe) works like this. It describes the most recent tag with hash of current commit. If none are found, it describes the current branch.

This is not an issue, it's the correct behavior
