### ISSUE TITLE
Add an action/button on the Repositories page to recover all repositories 

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#371]
After rebooting [this machine hosting a 8.1.1 Cockpit in development mode](https://be-scale-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=352), the Repositories pages shows no repositories, see below screenshot.

Add an action/button on this page to recover all repositories

![screen shot 2017-02-17 at 09 15 44](https://cloud.githubusercontent.com/assets/13795109/23057787/08af3d36-f4f2-11e6-858d-baacdbd37e17.png)

This should basically implement `ays discover`:

![screen shot 2017-02-17 at 09 22 49](https://cloud.githubusercontent.com/assets/13795109/23057945/c838df68-f4f2-11e6-8e65-498e3896fa4b.png)

**Comment by rkhamis** [comment]
That's because the redis isn't configured properly to be persistent.

I feel like this feature doesn't make sense.

**Comment by yveskerwyn** [comment]
Maybe not, but please elaborate.

Which Redis configuration is causing that repositories are not persistent?

Something that can/will be solved?

**Comment by rkhamis** [comment]
@yveskerwyn In dev mode, we don't configure redis to be persistent. It's up to the developer to configure AYS to use which redis-server and to configure that redis-server however they want. In case no specific changes are made (your case), AYS uses the jumpscale redis which is not persistent.
 
In production, we make sure it's persistent.

There's nothing to be solved, imho.
