### ISSUE TITLE
Add docs on how to configure cockpit

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jscockpit#372]
- Docs on how to configure cockpit to work with oauth
- Docs on how to configure cockpit to be in dev mode

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/jscockpit/blob/8.1.1/docs/installation/prep/Itsyou.online/configuration.md

**Comment by john-kheir** [comment]
- Make sure to explain that the first 2 lines are definitions
- check all english rules .. and make sure steps are readable (as i explained)

**Comment by john-kheir** [comment]
verified on 8.1.1
