### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#373]
Go to any cockpit_url/elfinder like http://192.168.28.67/elfinder

More paths:
http://192.168.28.194/jslib/bootstrap
http://192.168.28.194/jslib/bootstrap/css
http://192.168.28.194/jslib/bootstrap/fonts
http://192.168.28.194/jslib/bootstrap/js
http://192.168.28.194/jslib/codemirror
http://192.168.28.194/jslib/flatui
http://192.168.28.194/jslib/flatui/css
http://192.168.28.194/jslib/flatui/fonts
http://192.168.28.194/jslib/font-awesome
http://192.168.28.194/jslib/font-awesome/css
http://192.168.28.194/jslib/font-awesome/fonts
http://192.168.28.194/jslib/jquery
http://192.168.28.194/jslib/new-ui
http://192.168.28.194/jslib/old
http://192.168.28.194/jslib/old/adminmenu
http://192.168.28.194/jslib/old/bootstrap
http://192.168.28.194/jslib/old/breadcrumbs
http://192.168.28.194/jslib/old/codemirror
http://192.168.28.194/jslib/old/datatables
http://192.168.28.194/jslib/old/elfinder
http://192.168.28.194/jslib/old/images
http://192.168.28.194/jslib/old/jquery.form
http://192.168.28.194/jslib/old/elfinder/css
http://192.168.28.194/jslib/old/elfinder/img
http://192.168.28.194/jslib/old/elfinder/js
http://192.168.28.194/jslib/old/elfinder/js/proxy
http://192.168.28.194/jslib/old/jquery.form
http://192.168.28.194/jslib/swagger
http://192.168.28.194/jslib/swagger/css
http://192.168.28.194/jslib/swagger/fonts
http://192.168.28.194/jslib/swagger/images
http://192.168.28.194/jslib/swagger/lib
http://192.168.28.194/restmachine/system/atyourservice/cockpitUpdate
http://192.168.28.194/restmachine/system/atyourservice/deleteRuns
http://192.168.28.194/restmachine/system/atyourservice/reload
http://192.168.28.194/restmachine//system/contentmanager/bitbucketreload?spacename=e
http://192.168.28.194/restmachine//system/contentmanager/bitbucketreload
http://192.168.28.194/restmachine//system/contentmanager/modelobjectlist
http://192.168.28.194/restmachine//system/contentmanager/modelobjectlist?namespace=e&category=e&key=e
http://192.168.28.194/restmachine//system/contentmanager/modelobjectupdate
http://192.168.28.194/restmachine//system/contentmanager/modelobjectupdate?appname=e&actorname=e&key=e
http://192.168.28.194/restmachine/system/usermanager/delete?username=${name}
http://192.168.28.194/restmachine/system/usermanager/delete?username=e
http://192.168.28.194/system/.files
http://192.168.28.194/system/.files/css
http://192.168.28.194/system/.files/img
http://192.168.28.194/system/.files/js

**Actual result**
![screenshot from 2017-02-20 16-03-23](https://cloud.githubusercontent.com/assets/17981089/23128093/3c73184a-f786-11e6-99bf-759d427ba29d.png)

**Version**

JumpScale

    Core: v8.1.0-49-ge49328e
    Portal: v8.1.0-2-g1682cab

JSCockpit

    JSCockpit: 8.1.0rc2-38-g6f8488c

**Comment by rkhamis** [comment]
Directories have a proper response (400) on 8.1.1 and 8.2.0

rest apis still need fixing
