### ISSUE TITLE
ays destory isn't working

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#375]
**Description**
![screenshot from 2017-03-02 14-09-25](https://cloud.githubusercontent.com/assets/17981089/23506684/2743f4fc-ff52-11e6-8ea0-9bf83a749cc0.png)

**Version**

JumpScale

    Core: v8.1.0-68-g41fe9f2
    Portal: v8.1.0-2-g1682cab

JSCockpit

    JSCockpit: 8.1.0rc2-45-g14dcf7c

**Comment by john-kheir** [comment]
verified on 8.1.1
