### ISSUE TITLE
Run steps are new however it should be ok.

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jscockpit#377]
## First couple of steps are new in the portal (even after refresh) however they are ok in the reality
![b1](https://cloud.githubusercontent.com/assets/15011431/23657811/8f1675ba-0348-11e7-8b12-9ecd10854e5b.png)
![b2](https://cloud.githubusercontent.com/assets/15011431/23657813/90a4102c-0348-11e7-84e0-6a36a3cd68ad.png)

## Version

JumpScale

    Core: 8.1.1rc1-3-g3469b7f
    Portal: 8.1.1rc1

JSCockpit

    JSCockpit: 8.1.0rc2-46-gce1faa0

**Comment by rkhamis** [comment]
@john-kheir They both say new

**Comment by john-kheir** [comment]
@rkhamis Actually steps 1 , 2 and 3 ..already done which is creating g8client, vdc, vm and others .. so when u do ays run again step1 becomes fs.__.

**Comment by john-kheir** [comment]
## Verified on 8.1.1
