### ISSUE TITLE
Document how to configure AYS to use persistent redis

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#378]
**Description**
Reboot cockpit machine will reset the repository table in the portal.

**Steps**
- Create cockpit machine.
- Login to the cockpit portal
- Create a new repo
![screenshot from 2017-03-08 16-27-29](https://cloud.githubusercontent.com/assets/17981089/23707891/abd45788-041c-11e7-9a75-8972f16c77c3.png)
- Reboot this machine
- Login to the cockpit portal again 
- Check the repository table

**Actual Result**
![screenshot from 2017-03-08 16-28-33](https://cloud.githubusercontent.com/assets/17981089/23707911/c2d8f934-041c-11e7-98d3-aa45805148fb.png)

**Expected Result**
Reboot the cockpit machine shouldn't effect on reading the rpos

**Version**

JumpScale

    Core: 8.1.1rc1-3-g3469b7f
    Portal: 8.1.1rc1

JSCockpit

    JSCockpit: 8.1.0rc2-46-gce1faa0

**Comment by rkhamis** [comment]
This is bad configuration on your part.
If you install in dev mode, we don't configure AYS to use a persistent redis by default. If you want it to be persistent, you have to configure it yourself.

We do configure it in the blueprint for cockpit.


I'll close this issue

**Comment by yveskerwyn** [comment]
Can someone please add some details on how to configure this in the following documentation:
https://github.com/Jumpscale/jscockpit/blob/8.1.1/docs/installation/Using-Cuisine/using-cuisine.md

**Comment by xmonader** [comment]
@yveskerwyn  @rkhamis  pointed me to this https://github.com/Jumpscale/jumpscale_core8/blob/8.1.1/docs/AYS/configuration.md
