### ISSUE TITLE
Cockpit portal can't create a new user with 'CAPITAL character'

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#379]
**Description**
Cockpit portal can't create a new user with 'CAPITAL character'
![screenshot from 2017-03-08 16-48-27](https://cloud.githubusercontent.com/assets/17981089/23708679/73700f88-041f-11e7-80df-7aae4750297a.png)

**Version**

JumpScale

    Core: 8.1.1rc1-3-g3469b7f
    Portal: 8.1.1rc1

JSCockpit

    JSCockpit: 8.1.0rc2-46-gce1faa0

**Comment by rkhamis** [comment]
This is not a bug. The error message even specifies the user name constraints.

This, at most, is a feature request. One I see no need for.
