### ISSUE TITLE
Security: Local config.hrd has global access

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#380]
**Description**
The config.hrd file which has the root username and password is globally access without authentication need. 

**Steps**
- Install cockpit machine
- Download the config.hrd from the following link
http://192.168.28.50/elfinder/4e7153dd2f37816840735155f5660651?cmd=file&target=e60b085b27b52202760ab24031a01efa&current=616093e29007c89fe1278f9d3ce56586&download=1
- Replace the IP with your cockpit machine IP

**Config Data**
![screenshot from 2017-03-08 17-05-31](https://cloud.githubusercontent.com/assets/17981089/23709482/41057e86-0422-11e7-9084-9fe76023e678.png)

**Version**

JumpScale

    Core: 8.1.1rc1-3-g3469b7f
    Portal: 8.1.1rc1

JSCockpit

    JSCockpit: 8.1.0rc2-46-gce1faa0

**Comment by xmonader** [comment]
Not an issue: Only authenticated users can have access to the download links.
