### ISSUE TITLE
There is no param.cfg.organization parameter in /optvar/cfg/portals/main/config.hrd

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#386]
There is no param.cfg.organization parameter in /optvar/cfg/portals/main/config.hrd as its mentiont in this docs. 
https://github.com/Jumpscale/jscockpit/blob/8.1.1/docs/installation/prep/Itsyou.online/configuration.md
So please update the docs or edit the config file.

V 8.1.1

**Comment by yveskerwyn** [comment]
I had to add the entry I think

**Comment by yveskerwyn** [comment]
@islamTaha12, please validate the updated documentation, mentioning that you have to add the parameter param.cfg.organization, not setting it: https://github.com/Jumpscale/jscockpit/blob/8.1.1/docs/installation/prep/Itsyou.online/configuration.md

**Comment by islamTaha12** [comment]
validated
