### ISSUE TITLE
security:Cockpit API Portal is exposed without authentication

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#388]
**Description**
Anyone can access the portal API for the cockpit machine without need an authentication and he can expose any API if the cockpit in the development mode, however he will need a valid jwt to expose the API in the production mode.
![screenshot from 2017-03-20 17-59-58](https://cloud.githubusercontent.com/assets/17981089/24108848/8ad0be44-0d97-11e7-8263-aaed16317e49.png)

**Expected Result**
API portal and exposing the API using requests, curl or wget must required an authentication session.

*Version*
8.1.1

**Comment by rkhamis** [comment]
"If the cockpit is in development mode" <---- not an issue. We turn off oauth for dev mode which is well documented and at developer's own risk. This is secure in production.

**Comment by rkhamis** [comment]
Reopened to hide API not just protect API calls.

**Comment by rkhamis** [comment]
This can be done by embedding the swagger page in an iframe in the portal. It's not an elegant solution and since this is not a security issue, merely a preferential one, I'll close it
