### ISSUE TITLE
Get internal server error with special charachter names.

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#390]
**Description:**
Create a cloud space with '\n' name will generate an internal server error.
![screenshot from 2017-03-22 16-30-40](https://cloud.githubusercontent.com/assets/17981089/24203002/2f5f8824-0f1d-11e7-888b-1887a8875bef.png)

**Expected**
BP parser should handle special characters. 

**Version**
8.1.1

**Comment by yveskerwyn** [comment]
Please check whether this problem is the same or related the problem as reported here: https://github.com/Jumpscale/ays_jumpscale8/issues/207

**Comment by xmonader** [comment]
Now instance name must be digits or alphanumeric.
https://github.com/Jumpscale/jumpscale_portal8/commit/cc7b49b668c4485e0e0a4533e326705bc3dd31a0
