### ISSUE TITLE
many accounts with same name can be created

### ISSUE THREAD

**Issue by ahmedelsayed-93** [Jumpscale/jscockpit#393]
### blueprint 
this  blueprint should  create 3 cloudspaces in account  : **account_mcs**
![qwe3](https://cloud.githubusercontent.com/assets/24386820/24202400/94adafd2-0f1b-11e7-8190-4906e9d56631.png)
### steps
![qwe2](https://cloud.githubusercontent.com/assets/24386820/24201532/f9d9e4be-0f18-11e7-9231-f7c4c1020a1f.png)
### actual result
3 accounts were created instead of one 
![qwe1](https://cloud.githubusercontent.com/assets/24386820/24201525/f3d44b72-0f18-11e7-9048-2f768d3c3b72.png)

### SV
JumpScale
```
Core: 8.1.1rc1-14-ge9089f6
Portal: 8.1.1rc1-4-g5ff5f28
```
JSCockpit
```
JSCockpit: 8.1.0rc2-67-g49dee58
```

**Comment by rkhamis** [comment]
Like I explained. That's an OVC issue. We check if exists and create one if not.
Any "fixes" we do on AYS would be to avoid running into them, so basically workarounds. 

This should not be reported here.
