### ISSUE TITLE
doc on cockpit out of date for bot deployment

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#51]
please check docu on
https://gig.gitbooks.io/cockpit/content/deployer_bot/usage.html

this its not 100% up to date

also think the DNS is not correct, think its a subdomain of one of our domains 

also for me the bot didn't work, some error

**Comment by yveskerwyn** [comment]
Tried myself multiple times, on different environments and got into problems too, last problem was when trying to deploy the cockpit on du-conv-3:

g8cockpitbot, [27 Jun 2016 09:32]: 
Deployement of you cockpit in progress, please be patient.
You can follow progress using the /status command

Error during deployement : 502 Bad Gateway
b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
...

@zaibon can you look into it?

Once OK for you, I will validate and update the documentation

**Comment by zaibon** [comment]
@yveskerwyn you're error is clearly explained. : `Not egough ressouces available to provision the requested  mahcine`. Nothing to do with cockpit. the environement you use is full.

For the other errors I'll investigate

**Comment by yveskerwyn** [comment]
Yes I realize that, still trying to find an environment where I can test...

Can you comment on the comment: "DNS is not correct, think its a subdomain of one of our domains"?

**Comment by zaibon** [comment]
Not sure what this comment means. maybe Kristof can explain.

**Comment by yveskerwyn** [comment]
@zaibon got another error now:


***ERROR***

STEP:3, ACTION:install@action()
def install(self, service):
    machine = self.getMachine(service)
    service.hrd.set('machineid', machine.id)

    executor = machine.get_ssh_connection()
    if not service.hrd.get('publicip', ''):
        service.hrd.set('publicip', machine.space.model['publicipaddress'])
        service.hrd.set('sshport', executor.port)
        if len(service.producers['sshkey']) >= 1:
            sshkey = service.producers['sshkey'][0]
            executor.cuisine.core.hostname = service.instance
            executor.cuisine.ssh.authorize('root', sshkey.hrd.get('key.pub'))

    for child in service.children:
        child.hrd.set("ssh.addr", service.hrd.get("publicip"))
        child.hrd.set("ssh.port", service.hrd.get("sshport"))

    for port in service.hrd.getList('ports'):
        ss = port.split(':')
        if len(ss) == 2:
            self.open_port(service, requested_port=ss[1], public_port=ss[0])
        else:
            self.open_port(service, requested_port=port)
action: run                  runid:85.255.197.109:2201:cloudscalers      (OK)
RESULT:
 ((type:runtime.error)
