### ISSUE TITLE
cockpit error pages

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#55]
The following links are producing an error pages
https://quality-test.aydo2.com/cockpit/AYSTemplates
https://quality-test.aydo2.com/cockpit/AYSBlueprints
https://quality-test.aydo2.com/cockpit/Information
https://quality-test.aydo2.com/cockpit/cockpit/AYSTemplates?ayspath=ays_repo_example
https://quality-test.aydo2.com/cockpit/cockpit/AYSBlueprints?ayspath=ays_repo_example

**Comment by zaibon** [comment]
Is this issue still valid ?
Links are broken now, can't really see anything.
