### ISSUE TITLE
Error when deploying new Cockpit

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#56]
Below:
- the error
- the full conversation with @g8cockpitbot

Screenshots (14) are available on demand...

**Error Message**

Error during deployement : ERROR: RUN:77896453 3
-------
## step:1

step:1 (INIT)
- vdcfarm!main                                       ! install         OK 
- g8client!main                                      ! install         OK 
- sshkey!dns                                         ! install         OK 
- sshkey!main                                        ! install         OK 

## step:2

step:2 (INIT)
- dns_client!main1                                   ! install         OK 
- blueprint!pilot                                    ! install         OK 
- dns_client!main3                                   ! install         OK 
- dns_client!main2                                   ! install         OK 
- vdc!default                                        ! install         OK 

## step:3

step:3 (INIT)
- node!cockpitvm                                     ! install         OK 

## step:4

step:4 (INIT)
- os!pilot                                           ! install         OK 

## step:5

step:5 (INIT)
- cockpit!default                                    ! install         OK 
- app_docker!default                                 ! install         OK 

## step:6

step:6 (INIT)
- node!cockpit                                       ! install         OK 

## step:7

step:7 (ERROR)
- os!default                                         ! install         ERROR 

***ERROR***

STEP:7, ACTION:install@action()
def install(self, service):
    if 'sshkey' in service.producers:
        sshkey = service.producers['sshkey'][0]
        sshkey_priv = sshkey.hrd.get('key.priv')
        sshkey_pub = sshkey.hrd.get('key.pub')
    else:
        raise j.exceptions.NotFound("No sshkey found. please consume an sshkey service")

    print("authorize ssh key to machine")
    cuisine = self.getExecutor(service).cuisine

    cuisine.core.file_write('/root/.ssh/id_rsa', sshkey_priv, mode='0600')
    cuisine.core.file_write('/root/.ssh/id_rsa.pub', sshkey_pub, mode='0600')
    if cuisine.core.file_exists('/root/.ssh/authorized_keys'):
        cuisine.core.file_append('/root/.ssh/authorized_keys', sshkey_pub)
    else:
        cuisine.core.file_write('/root/.ssh/authorized_keys', sshkey_pub)

    self.dns(service=service)
    self.caddy(service=service)
    cuisine.apps.influxdb.start()
    cuisine.apps.mongodb.start()
    cuisine.apps.controller.start()
    self.portal(service=service)
    self.shellinaboxd(service=service)
    self.grafana(service=service)
    self.gid(service=service)
    self.cockpit(service=service)
    self.ays_repo(service=service)

    cuisine.user.passwd("root", j.data.idgenerator.generateGUID())
action: run                  runid:85.255.197.109:2202:root      (OK)
RESULT:
    True
 ((type:runtime.error)

 Please /start again.

**Conversation**

g8cockpitbot, [28 Jun 2016 09:59]: 
... Please /start again.

Yves KERWYN, [28 Jun 2016 10:10]: 
/start

g8cockpitbot, [28 Jun 2016 10:10]: 
Hello yveskerwyn !
Welcome to the G8 Cockpit deployer bot.
I'm here to help you create your very own G8 Cockpit.
I'm going to ask you a few questions during the process to know how you want your cockpit to be created.

Let's get to work.

QUESTION :
Please enter the name of organization you are deploying the cockpit for

Yves KERWYN, [28 Jun 2016 10:10]: 
demoorg

g8cockpitbot, [28 Jun 2016 10:10]: 
Please click on the following link and authorize us to verify you are part of the organization 'demoorg'
https://itsyou.online/v1/oauth/authorize?redirect_uri=https%3A%2F%2Fdeployer.barcelona.aydo.com%2Fcallback&scope=user%3Amemberof%3Ademoorg&state=yd2tizsmlnj1f1u9tw7f&response_type=code&client_id=G8cockpit

QUESTION :
Please enter the url of the G8 where to deploy your cockpit.

Yves KERWYN, [28 Jun 2016 10:11]: 
be-scale-1.demo.greenitglobe.com

g8cockpitbot, [28 Jun 2016 10:11]: 
QUESTION :
Please enter the login of your account on the G8 where to deploy the cockpit

Yves KERWYN, [28 Jun 2016 10:11]: 
yves

g8cockpitbot, [28 Jun 2016 10:11]: 
QUESTION :
Please enter the password of your account on the G8 where to deploy cockpit

Yves KERWYN, [28 Jun 2016 10:11]: 
*****

g8cockpitbot, [28 Jun 2016 10:11]: 
QUESTION :
Choose which account to use

Yves KERWYN, [28 Jun 2016 10:11]: 
Account of Yves

g8cockpitbot, [28 Jun 2016 10:11]: 
QUESTION :

"AtYourService Robot creation
"Please connect to telegram and talk to @botfather.
"execute the command /newbot and choose a name and username for your bot
"@botfather should give you a token, paste it here please :

Yves KERWYN, [28 Jun 2016 10:13]: 
220858953:AAGq0S_NrEdpcMwmM_zkBqSXdp_A8be_8Ew

g8cockpitbot, [28 Jun 2016 10:13]: 
QUESTION :
Please select the name of the virtual data center where to deploy the G8 Cockpit

Yves KERWYN, [28 Jun 2016 10:13]: 
default

g8cockpitbot, [28 Jun 2016 10:13]: 
QUESTION :
Please choose the domain you want to use for your cockpit

Yves KERWYN, [28 Jun 2016 10:13]: 
demoorg

g8cockpitbot, [28 Jun 2016 10:13]: 
QUESTION :
Please enter the url of the github repository where to store the ays repo of your cockpit. Please use the git version. The repo need to exists.

Yves KERWYN, [28 Jun 2016 10:13]: 
https://github.com/yveskerwyn/cockpit_gig_demoorg

g8cockpitbot, [28 Jun 2016 10:13]: 
Deployement of you cockpit in progress, please be patient.
You can follow progress using the /status command

**Comment by lzonneke** [comment]
duplicate
