### ISSUE TITLE
Various macro errors on Cockpit

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#57]
See:
- https://moehaha.barcelona.aydo.com/cockpit/AYSRepos
- https://moehaha.barcelona.aydo.com/cockpit/AYSInstances
- https://moehaha.barcelona.aydo.com/cockpit/AYSTemplates
- https://moehaha.barcelona.aydo.com/cockpit/AYSRuns
- https://moehaha.barcelona.aydo.com/cockpit/AYSBlueprints
- https://moehaha.barcelona.aydo.com/cockpit/Information

Also error in RAML Console:
- https://moehaha.barcelona.aydo.com/api/apidocs/index.html?raml=api.raml

**Comment by zaibon** [comment]
all the marcos error are due to oauth token expired: see https://github.com/Jumpscale/jscockpit/issues/47

**Comment by yveskerwyn** [comment]
logout/login didn't help @zaibon 

Any update on the fix?

**Comment by xmonader** [comment]
Not a problem anymore right?

**Comment by yveskerwyn** [comment]
No can be closed
