### ISSUE TITLE
CockpitBot can't connect through ssh which producing an error

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#61]
**Description:**
Installing the cockpit using the CockpitBot is always producing the following error:
`Error during deployement : ERROR: RUN:36000833 3
—---—
## step:1

step:1 (INIT)
- g8client!main                                      ! install         OK 
- sshkey!main                                        ! install         OK 
- vdcfarm!main                                       ! install         OK 
- sshkey!dns                                         ! install         OK 

## step:2

step:2 (INIT)
- dns_client!main3                                   ! install         OK 
- vdc!deploycock                                     ! install         OK 
- dns_client!main1                                   ! install         OK 
- blueprint!pilot                                    ! install         OK 
- dns_client!main2                                   ! install         OK 

## step:3

step:3 (ERROR)
- node!cockpitvm                                     ! install         ERROR 

## step:4

step:4 (INIT)
- os!pilot                                           ! install         INIT 

## step:5

step:5 (INIT)
- cockpit!deploycock                                 ! install         INIT 
- app_docker!deploycock                              ! install         INIT 

## step:6

step:6 (INIT)
- node!cockpit                                       ! install         INIT 

## step:7

step:7 (INIT)
- os!deploycock                                      ! install         INIT 

***ERROR***

STEP:3, ACTION:install@action()
def install(self, service):
    machine = self.getMachine(service)
    service.hrd.set('machineid', machine.id)

    executor = machine.get_ssh_connection()
    if not service.hrd.get('publicip', ''):
        service.hrd.set('publicip', machine.space.model['publicipaddress'])
        service.hrd.set('sshport', executor.port)
        if len(service.producers['sshkey']) >= 1:
            sshkey = service.producers['sshkey'][0]
            executor.cuisine.core.hostname = service.instance
            executor.cuisine.ssh.authorize('root', sshkey.hrd.get('key.pub'))

    for child in service.children:
        child.hrd.set("ssh.addr", service.hrd.get("publicip"))
        child.hrd.set("ssh.port", service.hrd.get("sshport"))

    for port in service.hrd.getList('ports'):
        ss = port.split(':')
        if len(ss) == 2:
            self.open_port(service, requested_port=ss[1], public_port=ss[0])
        else:
            self.open_port(service, requested_port=port)
action: run                  runid:85.255.197.73:2200:cloudscalers      (OK)
RESULT:
 ((type:runtime.error).`
****************************************************************************************************************************************************************************************************************************************************************

Investigating in the VM itself is showing the following error:
`*ERROR***********************************************************************************
action: install              runid:ays_12702130         (ERROR)
    actions.install.|
    path: /tmp/12702130/recipes/node.ovc/actions.py
RESULT:
    True
ERROR:
    Impossible to create SSH connection to 85.255.197.75:2200
[Tue05 09:45] - ...lib/JumpScale/tools/actions/Action.py:775  - ERROR    - 
*SOURCECODE******************************************************************************
*TRACEBACK*********************************************************************************

Traceback (most recent call last):
  File "/tmp/actions/ays_12702130/install.py", line 35, in install
    self.open_port(service, requested_port=ss[1], public_port=ss[0])
  File "/tmp/12702130/recipes/node.ovc/actions.py", line 52, in open_port
    executor = j.tools.executor.getSSHBased(service.hrd.get("publicip"), service.hrd.getInt("sshport"), 'root')
  File "/opt/jumpscale8//lib/JumpScale/tools/executor/ExecutorFactory.py", line 55, in getSSHBased
    self._executors[key] = ExecutorSSH(addr, port=port, login=login, passwd=passwd, debug=debug, checkok=checkok, al
low_agent=allow_agent, look_for_keys=look_for_keys, pushkey=pushkey,pubkey=pubkey)
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 27, in __init__
    self.sshclient.connectTest()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 170, in connectTest
    rc, out = self.execute(cmd, showout=False)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 204, in execute
    ch = self.transport.open_session()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 118, in transport
    if self.client is None:
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 141, in client
    raise j.exceptions.RuntimeError('Impossible to create SSH connection to %s:%s' % (self.addr, self.port))
OurExceptions.RuntimeError: ERROR: Impossible to create SSH connection to 85.255.197.75:2200 ((type:runtime.error)
[Tue05 09:45] - ...lib/JumpScale/tools/actions/Action.py:794  - ERROR    - 

******************************************************************************************
`
**AYS**
![screenshot from 2016-07-05 16-35-27](https://cloud.githubusercontent.com/assets/17981089/16588307/299ed1e6-42d7-11e6-8f71-b203a8b248c4.png)

![screenshot from 2016-07-05 16-34-02](https://cloud.githubusercontent.com/assets/17981089/16588379/5d7de47a-42d7-11e6-9888-1652ce03a2ea.png)

However I have ability to connect the machine:
![screenshot from 2016-07-05 16-35-49](https://cloud.githubusercontent.com/assets/17981089/16588372/57767e5c-42d7-11e6-8e49-2c6b204a09c9.png)

**Env**
https://be-g8-1.demo.greenitglobe.com

**Software**
JumpScale

    Core: 7.1.0b12
    Portal: 7.1.0b12

OpenvCloud

    Core: 2.1.0b12

OpenvStorage:

    openvstorage-backend-core: 1.6.1-eugene-updates.4-1
    alba: 0.9.7
    openvstorage-webapps: 2.6.1-eugene-updates.20-1
    openvstorage-backend-webapps: 1.6.1-eugene-updates.4-1
    openvstorage-core: 2.6.1-eugene-updates.20-1
    openvstorage-hc: 1.6.1-eugene-updates.4-1
    openvstorage-cinder-plugin: 1.1.1-eugene-updates.1-1
    openvstorage: 2.6.1-eugene-updates.20-1
    openvstorage-backend: 1.6.1-eugene-updates.4-1
    openvstorage-sdm: 1.5.1-eugene-updates.1-1

**Comment by lzonneke** [comment]
#65 
duplicate
