### ISSUE TITLE
Name of cloud space gets lower cased when installing Cockpit through AYS

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#62]
When specifying cockpit.name: 'Cockpit of Yves' in the blueprint a new cloud space gets creates with the name "cockpit of yves" ignoring the uppercases, and not using the existing cloud space "Cockpit of Yves".

Feature request: respect capitals in blueprints

**Comment by yveskerwyn** [comment]
Same behaviour when installing with the Deployer Chatbot, as reported here: https://github.com/Jumpscale/jscockpit/issues/81

**Comment by xmonader** [comment]
I've traced the issue and it's apparently from ServiceRecipe.py/newInstance method as it lowers the instance 
```instance = instance.lower()```
I don't think we can risk changing something internal in ays while we're a having a demo.

**Comment by lzonneke** [comment]
add comment in the deloybot which states this way of working in the first phase

**Comment by yveskerwyn** [comment]
While waiting for a better solution, I've updated the documentation about this
