### ISSUE TITLE
cockpit.name in blueprint is confusing -> cockpit.vdc

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#63]
In the blueprint for creating a new Cockpit:

cockpit.name: '...  is confusing...

It should be:
cockpit.vdc: ...

Since it is not the name of the cockpit, but rather the name of vdc that will host cockpitvm'

Also please don't use cockpit.cloudspace

Please change to cockpit.vdc

**Comment by rkhamis** [comment]
It's also going to be the name of the cockpit. Both the vdc and cockpit share a name when using the cockpit.g8 blueprint service

**Comment by zaibon** [comment]
We don't use the same blueprint anymore
