### ISSUE TITLE
Allow to change the name of the Cockpit VM in blueprint

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#64]
When using a [blueprint](https://github.com/Jumpscale/ays_jumpscale8/blob/master/_blueprints/blueprint.cockpit.g8/schema.hrd#L11) to install a Cockpit a VM name "cockpitvm" is created in cloud space as named by cockpit.name

Please allow to specify a name

Suggestion:

cockpit.vm: ...

**Comment by yveskerwyn** [comment]
Maybe keep it as is, but review the blueprint fields: cockpit.name, cockpit.vdc

**Comment by zaibon** [comment]
current blueprint leave the choice of the node used to the user.
