### ISSUE TITLE
No AYS instances created after confirmation of successful blueprint execution

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#67]
Cockpit: https://moehaha.barcelona.aydo.com/cockpit
AYS Repo: demo1

After executing, getting confirmation:
![blueprint-executed](https://cloud.githubusercontent.com/assets/13795109/16619680/7297b382-438f-11e6-961d-009d4856db92.png)

In AYS Repos:
![screen shot 2016-07-06 at 15 33 48](https://cloud.githubusercontent.com/assets/13795109/16619633/470700f6-438f-11e6-9645-e4a1f969f3c1.png)

Clicking Instances:
![screen shot 2016-07-06 at 15 33 54](https://cloud.githubusercontent.com/assets/13795109/16619663/5a058222-438f-11e6-98c7-c93690d83c99.png)

**Comment by lzonneke** [comment]
currently we need to load all services as workaround in the cockpit
