### ISSUE TITLE
List AYS repositories in a table

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#69]
List the AYS repositories in a table, consistent with design we use in the Cloud Broker Portal for items like Accounts - see second screenshot below

Now it really looks ugly and it doesn't provide an overview:

![screen shot 2016-07-06 at 16 17 41](https://cloud.githubusercontent.com/assets/13795109/16621057/3b635f50-4395-11e6-8f5f-0997919e3e5a.png)

![screen shot 2016-07-06 at 16 20 36](https://cloud.githubusercontent.com/assets/13795109/16621181/a111b6da-4395-11e6-9f3e-bcd1d063b887.png)

**Comment by grimpy** [comment]
Fixed at https://github.com/Jumpscale/jscockpit/commit/b8c5d6552a0b6b357b20a36f2072b44ddc28bb4f
