### ISSUE TITLE
Verify cockpit deployment

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jscockpit#7]
- Verify cockpit deployment
 - Test what happens if multiple users deploy at the same time  
  Current implementation is very simplistic. Need to check if two user try to deploy at the same time there is no issue.
 - Check if we can limite the question ask to the user. (dns_login, dns_password are good example of something the end user should not specify)
 - Verify portal configuration

How to start bot for cockpit deployment: 
execute the script located there : https://github.com/0-complexity/g8cockpit/blob/telegram_bot/scripts/cockpitbot.py
`jspython cockpitbot.py --token telegram_token`
Get the token by speaking to @botfather in telegram.

**Comment by despiegk** [comment]
script gone to install cockpit
where is it, please also put some doc into this repo referring to other info to read

**Comment by zaibon** [comment]
see https://gig.gitbooks.io/cockpit/content/docs/jscockpit/installation.html
