### ISSUE TITLE
cockpit_installation: Failed Cockpit deployment through Telegram

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#70]
## step:1

step:1 (INIT)
- sshkey!main                                        ! install         OK 
- g8client!main                                      ! install         OK 
- sshkey!dns                                         ! install         OK 
- vdcfarm!main                                       ! install         OK 
## step:2

step:2 (INIT)
- dns_client!main2                                   ! install         OK 
- blueprint!pilot                                    ! install         OK 
- vdc!cockpit-demo                                   ! install         OK 
- dns_client!main1                                   ! install         OK 
- dns_client!main3                                   ! install         OK 
## step:3

step:3 (ERROR)
- node!cockpitvm                                     ! install         ERROR 
## step:4

step:4 (INIT)
- os!pilot                                           ! install         INIT 
## step:5

step:5 (INIT)
- app_docker!cockpit-demo                            ! install         INIT 
- cockpit!cockpit-demo                               ! install         INIT 
## step:6

step:6 (INIT)
- node!cockpit                                       ! install         INIT 
## step:7

step:7 (INIT)
- os!cockpit-demo                                    ! install         INIT 

**_ERROR**_

STEP:3, ACTION:install@action()
def install(self, service):
    machine = self.getMachine(service)
    service.hrd.set('machineid', machine.id)

```
executor = machine.get_ssh_connection()
if not service.hrd.get('publicip', ''):
    service.hrd.set('publicip', machine.space.model['publicipaddress'])
    service.hrd.set('sshport', executor.port)
    if len(service.producers['sshkey']) >= 1:
        sshkey = service.producers['sshkey'][0]
        executor.cuisine.core.hostname = service.instance
        executor.cuisine.ssh.authorize('root', sshkey.hrd.get('key.pub'))

for child in service.children:
    child.hrd.set("ssh.addr", service.hrd.get("publicip"))
    child.hrd.set("ssh.port", service.hrd.get("sshport"))

for port in service.hrd.getList('ports'):
    ss = port.split(':')
    if len(ss) == 2:
        self.open_port(service, requested_port=ss[1], public_port=ss[0])
    else:
        self.open_port(service, requested_port=port)
```

action: run                  runid:85.255.197.88:2200:cloudscalers      (OK)
RESULT:
 ((type:runtime.error)

 Please /start again.

**Comment by lzonneke** [comment]
#65

**Comment by despiegk** [comment]
new FR created
