### ISSUE TITLE
cockpit_installation: Deployer Bot shows "left-over" tiles during conversation

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#71]
In the screenshot you see that the bot is asking for my G8 username, but still shows the environment “tiles” the choose from - "left-over" from previous questions: 

![screen shot 2016-07-08 at 09 40 53](https://cloud.githubusercontent.com/assets/13795109/16680781/66377ccc-44f1-11e6-9790-88ac88893101.png)

**Comment by abdulrahmantkhalifa** [comment]
validated

**Comment by zaibon** [comment]
Where is the code that fixed the issue?
