### ISSUE TITLE
Better text/message needed after user authorized access to his ItsYou.online profile to verify organization membership

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#76]
Once the user has authorized the chatbot to verify membership, you get the below - rather ugly - brower screen.

We need to show something still within the ItsYou.online context, simply saying that the membership was successfully verified, and that the user now can logged out and close the page...

![screen shot 2016-07-08 at 10 41 13](https://cloud.githubusercontent.com/assets/13795109/16682022/88daf61c-44f8-11e6-85b8-464e8b68a4b4.png)

**Comment by lzonneke** [comment]
Transfer to UI team

**Comment by lzonneke** [comment]
@samaradel can you take care of this one?

**Comment by samaradel** [comment]
sure..

**Comment by yveskerwyn** [comment]
https://github.com/Jumpscale/jscockpit/blob/master/deployer_bot/Oauth.py#L86

**Comment by yveskerwyn** [comment]
We need a message saying 2 things:

1. confirmation that access was granted to the chatbot

2. that the user now needs to go back to the chatbot for further instructions
