### ISSUE TITLE
Internal error when reloading services in Cockpit

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#77]
See screenshot

Cockpit: cockpit-demo.aydo2.com/cockpit/

@zaibon you have access

![screen shot 2016-07-08 at 11 39 49](https://cloud.githubusercontent.com/assets/13795109/16683547/c83f36d0-4500-11e6-99a5-9f2b6194f432.png)

**Comment by yveskerwyn** [comment]
Related to https://github.com/Jumpscale/jscockpit/issues/78

**Comment by zaibon** [comment]
It's indeed related to the #78 . It's not an error but the error message can be improve

**Comment by zaibon** [comment]
We don't reloead cockpit anymore in version 0.9
