### ISSUE TITLE
mvp-cockpit: Mal-formatted blueprint results in AYS behave in an unpredictable way [4h]

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#78]
When created a blueprint that starts like this: ```yaml

You get all kind of errors in the Cockpit Portal

**Comment by yveskerwyn** [comment]
Causes this other problem: https://github.com/Jumpscale/jscockpit/issues/77

**Comment by xmonader** [comment]
You will get this message if you try to execute invalid "yaml-wise" blueprint 
```
ERROR: Error during execution of the blueprint: ERROR: Could not process blueprint (load from yaml): path:'/opt/code/cockpit/a2/blueprints/2_next.yaml', line: '1', content: ###### ``` ###### error:while scanning for the next token found character '`' that cannot start any token in "<unicode string>", line 1, column 1: ``` ^ ((type:input.error) ((type:runtime.error)```

**Comment by rkhamis** [comment]
Maybe a nicer error message saying it's not valid YAML and where it failed or something

**Comment by zaibon** [comment]
I also want to add some other checks.
For example, when loading the blueprint, checking that all service template specified in the blueprint are available. I have a work in progress for it I'll create a PR when ready

**Comment by FastGeert** [comment]
perhaps add check for valid blueprint on adding through the portal explorer

**Comment by rkhamis** [comment]
Already fixed
