### ISSUE TITLE
Service info for a successfully installed service shows error message

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#80]
Cockpit: cockpit-demo.aydo2.com
Running on be-scale-2: https://be-scale-2.demo.greenitglobe.com/CBGrid/Cloud%20Space?id=31
Error message under "Edit files": **ERROR:could not find file /opt/code/cockpit/demo3/services/vdcfarm**

![screen shot 2016-07-08 at 16 53 44](https://cloud.githubusercontent.com/assets/13795109/16691339/9a6af2fe-452c-11e6-8e8f-3d1ff52af0ee.png)

**Comment by lzonneke** [comment]
#98 
duplicate
