### ISSUE TITLE
Also when deploying a new Cockpit via the Deployer Chatbot all uppercases are ignored

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#81]
Example: You have a cloud space ready, named "WhattIconsume", and in the conversation with the Deployer Chatbot you specify that you want the Cockpit be deployed there, you'll end up with a new cloud space, named "watticonsume" - see  screenshot

![screenshot from 2016-07-11 11-08-31](https://cloud.githubusercontent.com/assets/13795109/16728670/143c5f54-4768-11e6-8118-227d247c8da0.png)

Is related to the same wrong behaviour when deploying via AYS: https://github.com/Jumpscale/jscockpit/issues/62

**Comment by xmonader** [comment]
See https://github.com/Jumpscale/jscockpit/issues/62#issuecomment-233181454
