### ISSUE TITLE
Currently every blueprint contains G8 cloud account credentials under g8client__something

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#82]
Not sure what the right design would be, but here's a suggestion:
- Have the Cockpit remember/cache/store g8client credentials
- Allow blueprints to reference cached/store g8client credentials, without having to send the over
...

Not sure what the role of ItsYou.online could be here...

**Comment by yveskerwyn** [comment]
"by design"

I will update documentation

**Comment by lzonneke** [comment]
@yveskerwyn close this when its in the documentation

**Comment by rkhamis** [comment]
@yveskerwyn can we close this?
