### ISSUE TITLE
Error when deleting Repo

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#85]
See screenshot

![screen shot 2016-07-13 at 15 11 09](https://cloud.githubusercontent.com/assets/13795109/16804447/22edd88e-490c-11e6-9ef5-0c97604c7553.png)

**Comment by xmonader** [comment]
I can't reproduce it on an updated environment.

**Comment by yveskerwyn** [comment]
Just reproducted on the Moehaha Cockpit when trying to delete "yves_demo2": https://moehaha.barcelona.aydo.com/cockpit/repo?repo=yves_demo2

See result in below screenshot

<img width="1515" alt="screen shot 2016-07-18 at 16 39 21" src="https://cloud.githubusercontent.com/assets/13795109/16918640/a2d777dc-4d06-11e6-8a24-12af5e03c620.png">

**Comment by zaibon** [comment]
fix by #108
