### ISSUE TITLE
when login over ssh over http, then ays list does not work

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#86]
![image](https://cloud.githubusercontent.com/assets/6021844/16807376/6b62363a-4918-11e6-9c0e-3850e723b10e.png)

**Comment by rkhamis** [comment]
You need to be in the aysrepo before performing an ays action

**Comment by despiegk** [comment]
yes I do realize, but users will not know this

**Comment by despiegk** [comment]
so we need to make sure they get into the right directory or give them clear instructions
