### ISSUE TITLE
Cannot install blueprint because async param missing

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#87]
See screenshot

![screen shot 2016-07-14 at 10 43 43](https://cloud.githubusercontent.com/assets/13795109/16833697/b69db8d4-49b0-11e6-8846-cd16b9432436.png)

**Comment by xmonader** [comment]
How did you produce it? I can't reproduce it on the current installation?

**Comment by zaibon** [comment]
Can't reproduce with last version. close
