### ISSUE TITLE
You can only edit a blueprint in the explorer if it has the .txt extension

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#88]
In order to change a blueprint in the Cockpit Portal you need to rename it first with an .txt extension, if not the edit menu doesn't appear in the context menu of the blueprint in the Explorer

Not really blocking, but rather ugly for demo's

(probably a limitation of the Explorer)

**Comment by grimpy** [comment]
https://github.com/Jumpscale/jumpscale_portal8/commit/d2253ce1a6fffe39b7db51d83cd847d64105640b
