### ISSUE TITLE
Remove the "AYS" prefix from all the items in the "hamburger" menu 

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#89]
See the below screenshot of the left navigation menu

Change the titles/names as follows:
- AYS Repos -> Repositories
- AYS Instances -> Instances
- AYS Templates -> Templates
- AYS Runs -> Runs

Also do the same for the breadcrumb.

![screen shot 2016-07-14 at 11 32 43](https://cloud.githubusercontent.com/assets/13795109/16835013/c579c220-49b6-11e6-9b77-e02c15e13920.png)

**Comment by xmonader** [comment]
Fixed
