### ISSUE TITLE
Deleting Repos from Repositories table doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#96]
See screenshot

When trying to delete via the Repository Details page, same problem when trying delete via the Repository Details page, see second screenshot

![screen shot 2016-07-15 at 16 03 40](https://cloud.githubusercontent.com/assets/13795109/16876819/ccd4fa40-4aa5-11e6-8549-d8f068165a48.png)

![Uploading Screen Shot 2016-07-15 at 16.06.03.png…]()

**Comment by xmonader** [comment]
It works and I can't reproduce it.

**Comment by yveskerwyn** [comment]
Did you try on the Moehaha Cockpit?

What is your username on Itsyou.online?

**Comment by xmonader** [comment]
I tried it on cockpit-demo 
username: thabet

**Comment by yveskerwyn** [comment]
Please use the Moehaha Cockpit to reproduce, I've send you an invitation on ItsYou.online

Feel free do delete any older repo

**Comment by yveskerwyn** [comment]
https://moehaha.barcelona.aydo.com/cockpit/Repos

**Comment by lzonneke** [comment]
@islamtaha12 lease verify

**Comment by yveskerwyn** [comment]
@xmonader 
Please check the Moehaha Cockpit, just reproducted the error when trying to delete "yves_demo2": https://moehaha.barcelona.aydo.com/cockpit/repo?repo=yves_demo2

See result in below screenshot

<img width="1515" alt="screen shot 2016-07-18 at 16 39 21" src="https://cloud.githubusercontent.com/assets/13795109/16918640/a2d777dc-4d06-11e6-8a24-12af5e03c620.png">

**Comment by zaibon** [comment]
fix in #108
