### ISSUE TITLE
Error in the Instance page of the Cockpit

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#98]
The following link has an error
https://cockpit-demo-3.aydo2.com/cockpit/cockpit/Instance?shortkey=app_docker!watticonsume&ayspath=ays_cockpit

![screenshot from 2016-07-17 12-56-43](https://cloud.githubusercontent.com/assets/17981089/16900670/f8e7e4be-4c33-11e6-8b27-33a0b2668b74.png)

**Software Version**
0.9

**Comment by zaibon** [comment]
Problem comes from the fact that we have some special character in the path.
for example : ` /opt/code/cockpit/ays_cockpit/services/vdcfarm/!main/vdc/!devcockpit/node/!cockpitvm/`
explorer doesn't like to have `!` in the path. so I would remove this explorer  and let the user go through the explorer on the repository page.

**Comment by zaibon** [comment]
https://github.com/Jumpscale/jscockpit/commit/712b1136a4bf424d44f48db6a006d336b0fc5554
