### ISSUE TITLE
Error in "Go to shell" action in the Repo

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#99]
**Description**
"Go to shell" Action from the repo action menu is producing an error.

**Sequence**
- Create a repo
- Creata a BP and Execute it
- Press on "Go to Shell" from the drop down menu

**Actual Result"**
![screenshot from 2016-07-17 14-31-47](https://cloud.githubusercontent.com/assets/17981089/16900760/4d3f5ac6-4c37-11e6-8b05-0f6945b124d6.png)

**Comment by xmonader** [comment]
Apparently that method isn't defined yet?

**Comment by lzonneke** [comment]
We need to remove this from the UI for for now

**Comment by xmonader** [comment]
Not implemented  yet. Also the one in Simulate.

**Comment by yveskerwyn** [comment]
@zaibon thanks for checking #107 again since your fix didn't make it to my update
